const q = (base, extra) => ({ ...base, type: 'single_choice', ...extra });
const match = (base, extra) => ({ ...base, type: 'matching', ...extra });
const order = (base, extra) => ({ ...base, type: 'ordering', ...extra });
const short = (base, extra) => ({ ...base, type: 'short_answer', ...extra });

const tv4 = {
  grade: 4,
  book: 'Tiếng Việt 4 - Kết nối tri thức',
  subject: 'Tiếng Việt'
};

const tv5 = {
  grade: 5,
  book: 'Tiếng Việt 5 - Kết nối tri thức',
  subject: 'Tiếng Việt'
};

module.exports = [
  q(tv4, { topic: 'Trình tự kể chuyện', source_unit: 'Trải nghiệm và khám phá', source_lesson: 'Viết bài văn kể lại sự việc', skill_tag: ['writing', 'sequence'], difficulty: 'vận dụng', question: 'Để bài văn kể lại một sự việc mạch lạc, cách sắp xếp nào thường phù hợp nhất?', options: { A: 'Theo trình tự diễn biến của sự việc và làm rõ chi tiết chính', B: 'Nghĩ đến chi tiết nào viết ngay chi tiết đó', C: 'Viết phần kết trước, bỏ qua nguyên nhân', D: 'Lặp lại một ý quan trọng nhiều lần là đủ' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Câu chủ đề trong đoạn văn', source_unit: 'Mỗi người một vẻ', source_lesson: 'Đọc và viết đoạn văn', skill_tag: ['writing', 'cohesion'], difficulty: 'thông hiểu', question: 'Câu chủ đề trong đoạn văn thường có vai trò gì?', options: { A: 'Nêu ý chính để các câu sau làm rõ thêm', B: 'Chỉ dùng để kể chuyện cười cho hấp dẫn', C: 'Thay thế cho toàn bộ các câu còn lại', D: 'Không liên quan đến nội dung đoạn văn' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Tính từ', source_unit: 'Niềm vui sáng tạo', source_lesson: 'Luyện tập về tính từ', skill_tag: ['grammar', 'effect'], difficulty: 'vận dụng', question: 'Trong câu “Dòng sông hiền hoà lấp lánh dưới nắng”, từ nào là tính từ?', options: { A: 'hiền hoà', B: 'dòng', C: 'dưới', D: 'nắng' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Dấu gạch ngang', source_unit: 'Chắp cánh ước mơ', source_lesson: 'Dấu gạch ngang', skill_tag: ['punctuation', 'usage'], difficulty: 'vận dụng', question: 'Trong đoạn đối thoại, dấu gạch ngang thường dùng để:', options: { A: 'Đánh dấu lời nói trực tiếp của nhân vật', B: 'Tách vị ngữ khỏi chủ ngữ', C: 'Thay cho dấu chấm hết câu', D: 'Nối các tiếng bắt buộc trong mọi từ ghép' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Viết thư', source_unit: 'Chắp cánh ước mơ', source_lesson: 'Viết thư', skill_tag: ['functional-writing', 'purpose'], difficulty: 'vận dụng', question: 'Trong lá thư hỏi thăm bạn, phần nào giúp người đọc hiểu rõ mục đích bức thư nhất?', options: { A: 'Đoạn nêu lí do viết thư và nội dung hỏi thăm', B: 'Chỉ ghi địa chỉ người gửi', C: 'Chỉ viết lời chào mà không có nội dung chính', D: 'Chỉ kí tên cuối thư' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Báo cáo thảo luận nhóm', source_unit: 'Mỗi người một vẻ', source_lesson: 'Nói và nghe', skill_tag: ['functional-writing', 'organization'], difficulty: 'vận dụng', question: 'Một bản báo cáo thảo luận nhóm tốt cần có điểm nào sau đây?', options: { A: 'Nêu rõ nhiệm vụ, ý kiến chính và kết quả thống nhất', B: 'Ghi toàn bộ lời nói vụn vặt của từng bạn', C: 'Chỉ nêu cảm xúc của người viết', D: 'Viết càng dài càng tốt dù thiếu trọng tâm' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Đọc hiểu chi tiết gợi cảm xúc', source_unit: 'Sống để yêu thương', source_lesson: 'Đọc hiểu văn bản', skill_tag: ['reading', 'inference'], difficulty: 'vận dụng', passage: 'Mưa vừa tạnh. Trên lá bàng còn đọng những giọt nước nhỏ long lanh. Sân trường thơm mùi đất ướt, lũ chim sẻ ríu ran trên mái ngói.', question: 'Chi tiết nào góp phần gợi rõ nhất cảm giác tươi mới sau mưa?', options: { A: 'Giọt nước long lanh và mùi đất ướt', B: 'Mái ngói ở sân trường', C: 'Số lượng chim sẻ', D: 'Thời gian mưa tạnh đã bao lâu' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Chọn từ nối phù hợp', source_unit: 'Quê hương trong tôi', source_lesson: 'Liên kết câu', skill_tag: ['grammar', 'cohesion'], difficulty: 'vận dụng', question: 'Chọn từ ngữ thích hợp để liên kết: “Trời bắt đầu nắng to, ... chúng em chuyển chậu cây vào chỗ râm.”', options: { A: 'vì thế', B: 'mặc dù', C: 'nhưng', D: 'nếu' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Nhân hoá', source_unit: 'Niềm vui sáng tạo', source_lesson: 'Biện pháp nghệ thuật', skill_tag: ['reading', 'meaning'], difficulty: 'thông hiểu', question: 'Câu nào sử dụng biện pháp nhân hoá?', options: { A: 'Những hàng cây đứng lặng nghe tiếng trống trường', B: 'Hàng cây rất cao và xanh', C: 'Có nhiều cây trước sân', D: 'Lá cây màu xanh đậm' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Nhan đề phù hợp', source_unit: 'Sống để yêu thương', source_lesson: 'Đọc hiểu văn bản', skill_tag: ['reading', 'main-idea'], difficulty: 'vận dụng', passage: 'Tối nào ông cũng ngồi trước hiên đan lại chiếc rổ cũ. Tôi ngồi cạnh, nghe ông kể chuyện làng xưa và học cách kiên nhẫn với từng nan tre nhỏ.', question: 'Nhan đề nào phù hợp nhất với đoạn văn?', options: { A: 'Bài học bên hiên nhà', B: 'Chiếc xe đạp mới', C: 'Một buổi đi chợ', D: 'Trận bóng chiều hè' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Mở bài phù hợp', source_unit: 'Trải nghiệm và khám phá', source_lesson: 'Viết bài văn kể chuyện', skill_tag: ['writing', 'organization'], difficulty: 'vận dụng', question: 'Nếu viết bài kể về một lần giúp đỡ bạn, cách mở bài nào phù hợp hơn?', options: { A: 'Giới thiệu ngắn gọn hoàn cảnh xảy ra việc em giúp bạn', B: 'Liệt kê tất cả môn học em thích', C: 'Nói ngay kết luận mà không nhắc sự việc', D: 'Chép một câu thơ không liên quan rồi dừng lại' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Liên kết đoạn văn', source_unit: 'Vì một thế giới bình yên', source_lesson: 'Viết đoạn văn', skill_tag: ['cohesion', 'writing'], difficulty: 'vận dụng', question: 'Muốn các câu trong đoạn liên kết tốt hơn, người viết nên làm gì?', options: { A: 'Sử dụng từ ngữ nối và giữ các câu cùng hướng vào một ý chính', B: 'Đưa thật nhiều ý khác nhau vào cùng một đoạn', C: 'Thay đổi chủ đề liên tục cho sinh động', D: 'Mỗi câu dùng một cách xưng hô khác nhau' }, correct_answer: 'A' }),
  order(tv4, { topic: 'Sắp xếp đoạn kể việc tốt', source_unit: 'Sống để yêu thương', source_lesson: 'Viết đoạn văn kể việc làm tốt', skill_tag: ['writing', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp các ý để tạo thành trình tự kể việc làm tốt hợp lí.', items: [ { label: 'Nêu hoàn cảnh xảy ra sự việc', correct_position: 1 }, { label: 'Kể việc em đã làm', correct_position: 2 }, { label: 'Nêu kết quả và điều em rút ra', correct_position: 3 } ] }),
  match(tv4, { topic: 'Ghép mục đích với kiểu văn bản', source_unit: 'Nhiều chủ điểm', source_lesson: 'Đọc và viết văn bản', skill_tag: ['functional-writing', 'matching'], difficulty: 'vận dụng', question: 'Ghép mục đích với kiểu văn bản phù hợp.', items: [ { label: 'Hỏi thăm một người bạn', correct_match: 'Viết thư' }, { label: 'Thông báo kết quả làm việc của nhóm', correct_match: 'Báo cáo' }, { label: 'Kể lại một việc đáng nhớ', correct_match: 'Bài văn kể chuyện' } ], option_pool: ['Viết thư', 'Báo cáo', 'Bài văn kể chuyện'] }),
  short(tv4, { topic: 'Từ ngữ gợi tả', source_unit: 'Quê hương trong tôi', source_lesson: 'Đọc hiểu', skill_tag: ['reading', 'short-answer'], difficulty: 'vận dụng', question: 'Viết một từ ngữ gợi tả thích hợp để hoàn thành câu: “Cánh đồng lúa chín vàng ... dưới nắng chiều.”', correct_answer: 'óng ả' }),
  q(tv4, { topic: 'Chi tiết tiêu biểu khi tả người', source_unit: 'Mỗi người một vẻ', source_lesson: 'Viết bài văn miêu tả', skill_tag: ['writing', 'portrait'], difficulty: 'vận dụng', question: 'Khi tả một người thân, chi tiết nào thường giúp nhân vật hiện lên rõ hơn?', options: { A: 'Một vài nét ngoại hình và hoạt động, tính cách tiêu biểu', B: 'Liệt kê đầy đủ tất cả số đo của người đó', C: 'Chỉ viết “rất tốt” nhiều lần', D: 'Bỏ qua mọi chi tiết cụ thể để bài ngắn hơn' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Cảm xúc của người viết', source_unit: 'Sống để yêu thương', source_lesson: 'Đọc hiểu', skill_tag: ['reading', 'inference'], difficulty: 'vận dụng', passage: 'Mẹ cẩn thận gấp từng bộ quần áo cho tôi trước chuyến đi xa. Bàn tay mẹ thoăn thoắt, còn tôi bỗng thấy sống mũi cay cay.', question: 'Từ “cay cay” trong đoạn văn cho thấy người kể đang có cảm xúc gì?', options: { A: 'Xúc động, thương mẹ', B: 'Giận dữ vì phải đi xa', C: 'Ngạc nhiên vì quần áo quá nhiều', D: 'Buồn ngủ vì chuẩn bị lâu' }, correct_answer: 'A' }),
  q(tv4, { topic: 'Câu kết đoạn', source_unit: 'Trải nghiệm và khám phá', source_lesson: 'Viết đoạn văn', skill_tag: ['writing', 'organization'], difficulty: 'vận dụng', question: 'Câu kết đoạn nào phù hợp nhất cho đoạn văn kể về một lần em nhặt được của rơi và trả lại người mất?', options: { A: 'Việc làm nhỏ ấy khiến em hiểu rằng trung thực luôn đáng quý.', B: 'Chiều hôm đó trời nhiều mây hơn buổi sáng.', C: 'Em vẫn còn thích ăn món bánh ngọt ngoài cổng trường.', D: 'Bạn em học giỏi Toán hơn em rất nhiều.' }, correct_answer: 'A' }),

  q(tv5, { topic: 'Bài văn tả cảnh', source_unit: 'Thiên nhiên kì thú', source_lesson: 'Viết bài văn tả cảnh', skill_tag: ['writing', 'description'], difficulty: 'vận dụng', question: 'Khi tả cảnh biển buổi sáng, chi tiết nào giúp đoạn văn giàu hình ảnh hơn cả?', options: { A: 'Màu trời, tiếng sóng, ánh nắng và hoạt động của thuyền bè', B: 'Chỉ nêu tên địa điểm một lần', C: 'Liệt kê các con số không liên quan', D: 'Chỉ nói “cảnh rất đẹp” nhiều lần' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Bài văn tả người', source_unit: 'Vẻ đẹp cuộc sống', source_lesson: 'Viết bài văn tả người', skill_tag: ['writing', 'portrait'], difficulty: 'vận dụng', question: 'Muốn tả người chân thực, người viết nên chú ý nhất đến điều gì?', options: { A: 'Chọn chi tiết ngoại hình, cử chỉ và nét tính cách nổi bật', B: 'Chỉ chép lại một đoạn văn mẫu có sẵn', C: 'Bỏ qua hoạt động của nhân vật', D: 'Càng dùng nhiều từ khen chung chung càng tốt' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Quan hệ từ', source_unit: 'Vẻ đẹp cuộc sống', source_lesson: 'Cách nối các vế câu ghép', skill_tag: ['grammar', 'logic'], difficulty: 'vận dụng', question: 'Cặp quan hệ từ nào biểu thị quan hệ nguyên nhân - kết quả?', options: { A: 'vì ... nên ...', B: 'tuy ... nhưng ...', C: 'nếu ... thì ...', D: 'không những ... mà còn ...' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Nêu ý kiến phản đối', source_unit: 'Thế giới của chúng ta', source_lesson: 'Viết đoạn văn nêu ý kiến', skill_tag: ['argument', 'writing'], difficulty: 'vận dụng', question: 'Khi nêu ý kiến phản đối việc xả rác bừa bãi, cách viết nào thuyết phục hơn?', options: { A: 'Nêu rõ quan điểm, lí do và tác hại cụ thể của hành vi đó', B: 'Chỉ viết “Em không thích” rồi dừng lại', C: 'Chuyển sang kể chuyện cá nhân không liên quan', D: 'Nêu thật nhiều cảm xúc nhưng không có lí lẽ nào' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Đoạn văn bày tỏ cảm xúc', source_unit: 'Hương sắc trăm miền', source_lesson: 'Viết đoạn văn thể hiện cảm xúc', skill_tag: ['emotion', 'writing'], difficulty: 'vận dụng', question: 'Để đoạn văn bày tỏ cảm xúc chân thật hơn, người viết nên:', options: { A: 'Gắn cảm xúc với những chi tiết, hình ảnh cụ thể đã quan sát', B: 'Chỉ dùng những lời khen rất chung chung', C: 'Không cần nêu chi tiết nào vì cảm xúc tự rõ', D: 'Lặp lại một câu cảm thán nhiều lần' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Đọc hiểu ý chính', source_unit: 'Tiếp bước cha ông', source_lesson: 'Đọc hiểu văn bản', skill_tag: ['reading', 'main-idea'], difficulty: 'vận dụng', passage: 'Buổi sinh hoạt dưới cờ hôm ấy, cả sân trường lặng đi khi thầy kể về những người lính trẻ đã hi sinh để bảo vệ Tổ quốc. Lá cờ trên cao phần phật trong gió, còn chúng tôi ai cũng thấy lòng mình chững lại.', question: 'Ý chính của đoạn văn là gì?', options: { A: 'Sự xúc động và lòng biết ơn khi nghe kể về những người hi sinh vì Tổ quốc', B: 'Tả chi tiết cấu tạo của lá cờ', C: 'Kể chuyện chơi đùa ở sân trường', D: 'Giới thiệu giờ ra chơi buổi sáng' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Từ ngữ liên kết', source_unit: 'Hương sắc trăm miền', source_lesson: 'Liên kết câu và đoạn', skill_tag: ['cohesion', 'grammar'], difficulty: 'vận dụng', question: 'Trong câu “Trời đổ mưa lớn, ... đoàn tham quan vẫn tiếp tục đúng kế hoạch”, từ nối nào phù hợp nhất?', options: { A: 'nhưng', B: 'vì', C: 'nếu', D: 'nên' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Mở bài gián tiếp', source_unit: 'Thiên nhiên kì thú', source_lesson: 'Viết bài văn tả cảnh', skill_tag: ['writing', 'organization'], difficulty: 'vận dụng', question: 'Mở bài nào được xem là gián tiếp khi tả cảnh cánh đồng quê?', options: { A: 'Từ mùi rơm mới sau cơn mưa, em nhớ ngay đến cánh đồng quê mỗi mùa gặt.', B: 'Em tả cánh đồng quê em.', C: 'Cánh đồng là nơi có nhiều lúa.', D: 'Bài văn này nói về cánh đồng.' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Chi tiết tiêu biểu khi tả người', source_unit: 'Vẻ đẹp cuộc sống', source_lesson: 'Viết bài văn tả người', skill_tag: ['writing', 'portrait'], difficulty: 'vận dụng', question: 'Trong bài văn tả cô giáo, chi tiết nào thường có sức gợi hơn?', options: { A: 'Nụ cười, ánh mắt và cách cô kiên nhẫn hướng dẫn học sinh', B: 'Chỉ ghi năm sinh của cô', C: 'Liệt kê đồ dùng trong lớp', D: 'Nêu tên trường mà không nói gì về cô' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Câu kết bài', source_unit: 'Thế giới của chúng ta', source_lesson: 'Viết đoạn, bài văn', skill_tag: ['writing', 'organization'], difficulty: 'vận dụng', question: 'Câu kết bài nào phù hợp hơn cho bài văn nêu ý kiến về việc đọc sách?', options: { A: 'Vì thế, em mong mỗi bạn đều dành thời gian đọc sách để hiểu biết và sống đẹp hơn.', B: 'Ngoài ra, hôm nay trời khá nóng.', C: 'Em đã ăn sáng trước khi đi học.', D: 'Bạn Lan ngồi cạnh em rất thích đá cầu.' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Đọc hiểu hàm ý của từ ngữ', source_unit: 'Hương sắc trăm miền', source_lesson: 'Đọc hiểu', skill_tag: ['reading', 'inference'], difficulty: 'vận dụng', passage: 'Con đường làng sau mùa gặt bỗng rộng ra, vàng óng và thơm mùi rạ mới. Bà tôi bảo, chỉ cần bước chân trên lối ấy thôi cũng đủ nghe quê nhà gọi khẽ trong tim.', question: 'Từ “gọi khẽ trong tim” gợi lên điều gì?', options: { A: 'Tình cảm tha thiết, gắn bó với quê hương', B: 'Âm thanh thật sự phát ra từ con đường', C: 'Sự sợ hãi khi đi một mình', D: 'Tiếng nói của bà vang rất to' }, correct_answer: 'A' }),
  order(tv5, { topic: 'Sắp xếp đoạn nêu ý kiến', source_unit: 'Thế giới của chúng ta', source_lesson: 'Viết đoạn văn nêu ý kiến', skill_tag: ['argument', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp ý để tạo thành đoạn văn nêu ý kiến hợp lí.', items: [ { label: 'Nêu ý kiến của em', correct_position: 1 }, { label: 'Đưa ra lí do và dẫn chứng', correct_position: 2 }, { label: 'Khẳng định lại hoặc nêu mong muốn', correct_position: 3 } ] }),
  match(tv5, { topic: 'Ghép mục đích với cách viết', source_unit: 'Nhiều chủ điểm', source_lesson: 'Viết các kiểu đoạn văn', skill_tag: ['writing', 'matching'], difficulty: 'vận dụng', question: 'Ghép mục đích với cách viết phù hợp nhất.', items: [ { label: 'Muốn thuyết phục người đọc', correct_match: 'Nêu ý kiến kèm lí lẽ' }, { label: 'Muốn người đọc hình dung cảnh vật', correct_match: 'Chọn chi tiết gợi tả' }, { label: 'Muốn người đọc hiểu cảm xúc của em', correct_match: 'Gắn cảm xúc với chi tiết cụ thể' } ], option_pool: ['Nêu ý kiến kèm lí lẽ', 'Chọn chi tiết gợi tả', 'Gắn cảm xúc với chi tiết cụ thể'] }),
  short(tv5, { topic: 'Từ ngữ gợi hoà bình', source_unit: 'Thế giới của chúng ta', source_lesson: 'Đọc hiểu', skill_tag: ['reading', 'short-answer'], difficulty: 'vận dụng', question: 'Viết một từ ngữ gợi không khí yên bình để hoàn thành câu: “Buổi chiều trên cánh đồng thật ...”.', correct_answer: 'êm ả' }),
  q(tv5, { topic: 'Lựa chọn dẫn chứng', source_unit: 'Tiếp bước cha ông', source_lesson: 'Viết đoạn văn nêu ý kiến', skill_tag: ['argument', 'reasoning'], difficulty: 'vận dụng', question: 'Nếu muốn thuyết phục bạn chăm đọc sách lịch sử, dẫn chứng nào phù hợp hơn cả?', options: { A: 'Đọc sách lịch sử giúp hiểu quá khứ và thêm trân trọng hiện tại', B: 'Sách lịch sử dày nên cầm rất chắc tay', C: 'Bìa sách thường có nhiều màu đẹp', D: 'Ai cũng phải thích cùng một loại sách' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Chọn nhan đề', source_unit: 'Vẻ đẹp cuộc sống', source_lesson: 'Đọc hiểu văn bản', skill_tag: ['reading', 'main-idea'], difficulty: 'vận dụng', passage: 'Bố về muộn sau buổi trực nhưng vẫn cúi xuống sửa lại chiếc đèn học cho tôi. Ánh đèn vừa sáng lên, tôi bỗng thấy căn phòng nhỏ ấm hơn hẳn.', question: 'Nhan đề nào phù hợp nhất với đoạn văn?', options: { A: 'Ánh đèn của bố', B: 'Chiếc bàn học cũ', C: 'Buổi tối mất điện', D: 'Cuộc thi thể thao ở trường' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Biện pháp so sánh', source_unit: 'Nghệ thuật muôn màu', source_lesson: 'Đọc hiểu và nghệ thuật', skill_tag: ['reading', 'meaning'], difficulty: 'thông hiểu', question: 'Câu nào có sử dụng biện pháp so sánh?', options: { A: 'Tiếng suối trong như tiếng hát xa.', B: 'Tiếng suối chảy trong rừng.', C: 'Suối ở rất xa bản làng.', D: 'Tiếng hát của bạn vang lên.' }, correct_answer: 'A' }),
  q(tv5, { topic: 'Từ thay thế để liên kết', source_unit: 'Hương sắc trăm miền', source_lesson: 'Liên kết câu và đoạn', skill_tag: ['cohesion', 'application'], difficulty: 'vận dụng', question: 'Trong đoạn văn nói về “cây phượng”, từ nào có thể dùng thay thế để tránh lặp mà vẫn liên kết tốt?', options: { A: 'loài cây ấy', B: 'con vật ấy', C: 'bài học ấy', D: 'việc làm ấy' }, correct_answer: 'A' })
];
