const q = (base, extra) => ({ ...base, type: 'single_choice', ...extra });
const match = (base, extra) => ({ ...base, type: 'matching', ...extra });
const order = (base, extra) => ({ ...base, type: 'ordering', ...extra });

const kh4 = {
  grade: 4,
  book: 'Khoa học 4 - Kết nối tri thức',
  subject: 'Khoa học'
};

const kh5 = {
  grade: 5,
  book: 'Khoa học 5 - Kết nối tri thức',
  subject: 'Khoa học'
};

module.exports = [
  q(kh4, { topic: 'Nước sạch và an toàn', source_unit: 'Chất', source_lesson: 'Sự ô nhiễm và bảo vệ nguồn nước', skill_tag: ['science-life', 'reasoning'], difficulty: 'vận dụng', question: 'Nước mưa hứng trong chậu ngoài sân nhìn khá trong. Vì sao vẫn không nên uống ngay?', options: { A: 'Vì nước có thể lẫn bụi bẩn, vi sinh vật hoặc chất bẩn từ môi trường', B: 'Vì nước mưa luôn là nước mặn', C: 'Vì nước trong thì chắc chắn không có khoáng chất', D: 'Vì mọi loại nước đều phải nhuộm màu mới an toàn' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Không khí và sự cháy', source_unit: 'Chất', source_lesson: 'Không khí và sự cháy', skill_tag: ['experiment', 'reasoning'], difficulty: 'thông hiểu', question: 'Khi úp cốc lên ngọn nến đang cháy, ngọn nến tắt dần vì:', options: { A: 'Không khí cần cho sự cháy trong cốc giảm dần', B: 'Ánh sáng trong phòng làm nến yếu đi', C: 'Cốc thuỷ tinh làm sáp nến biến mất ngay', D: 'Ngọn nến chỉ cháy được khi có gió mạnh' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Phòng chống bão', source_unit: 'Chất', source_lesson: 'Gió, bão và phòng chống bão', skill_tag: ['safety', 'application'], difficulty: 'vận dụng', question: 'Trước khi bão đến, việc làm nào của gia đình là hợp lí nhất?', options: { A: 'Chằng chống nhà cửa và cất gọn vật dễ bị gió cuốn', B: 'Mở hết cửa sổ để gió lưu thông mạnh hơn', C: 'Ra ngoài đồng xem mây bão kéo đến', D: 'Tự ý bơi qua vùng nước ngập để quan sát' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Âm thanh trong cuộc sống', source_unit: 'Năng lượng', source_lesson: 'Âm thanh', skill_tag: ['sound', 'application'], difficulty: 'thông hiểu', question: 'Vì sao học sinh cần nói vừa đủ nghe trong lớp?', options: { A: 'Âm thanh quá lớn dễ gây ồn, làm người khác mất tập trung', B: 'Nói nhỏ thì câu chữ tự biến thành chữ viết', C: 'Âm thanh nhỏ luôn truyền nhanh hơn âm thanh lớn', D: 'Nói to giúp bài học ngắn lại' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Ánh sáng và bóng tối', source_unit: 'Năng lượng', source_lesson: 'Ánh sáng và bóng tối', skill_tag: ['light', 'experiment'], difficulty: 'vận dụng', question: 'Để bóng của một đồ vật trên tường rõ hơn, cách nào phù hợp nhất?', options: { A: 'Chiếu nguồn sáng vào vật và để vật chắn giữa đèn với tường', B: 'Đặt vật ở sau lưng người quan sát, không cần đèn', C: 'Chỉ cần mở to mắt nhìn mà không cần nguồn sáng', D: 'Để nhiều vật chắn chồng kín mọi phía' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Truyền nhiệt', source_unit: 'Năng lượng', source_lesson: 'Nóng, lạnh và vật dẫn nhiệt', skill_tag: ['energy', 'reasoning'], difficulty: 'thông hiểu', question: 'Tay cầm nồi thường làm bằng nhựa hoặc gỗ vì:', options: { A: 'Các vật đó dẫn nhiệt kém hơn kim loại, giúp cầm đỡ nóng tay', B: 'Các vật đó làm thức ăn chín nhanh hơn', C: 'Nhựa và gỗ luôn nặng hơn kim loại', D: 'Kim loại không dùng được trong nhà bếp' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Điều kiện sống của thực vật', source_unit: 'Thực vật và động vật', source_lesson: 'Nhu cầu sống của thực vật', skill_tag: ['biology', 'inference'], difficulty: 'vận dụng', question: 'Hai chậu cây được tưới nước như nhau, nhưng một chậu để nơi thiếu ánh sáng lâu ngày. Kết quả dễ xảy ra là:', options: { A: 'Cây để nơi thiếu sáng sinh trưởng kém hơn', B: 'Cây thiếu sáng sẽ ra hoa nhiều hơn chắc chắn', C: 'Hai cây phát triển giống hệt nhau vì cùng được tưới nước', D: 'Cây thiếu sáng tự tạo thêm ánh sáng cho mình' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Nhu cầu sống của động vật', source_unit: 'Thực vật và động vật', source_lesson: 'Nhu cầu sống của động vật', skill_tag: ['biology', 'application'], difficulty: 'vận dụng', question: 'Nuôi thỏ trong lồng quá chật, ít được cho ăn và không có nước sạch có thể dẫn đến điều gì?', options: { A: 'Thỏ dễ bị yếu và chậm lớn vì điều kiện sống không phù hợp', B: 'Thỏ sẽ khoẻ hơn vì ít phải vận động', C: 'Thỏ không cần nước nếu đã ăn rau', D: 'Lồng chật giúp thỏ thông minh hơn' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Nấm có ích và nấm có hại', source_unit: 'Nấm', source_lesson: 'Nấm trong đời sống', skill_tag: ['classification', 'science-life'], difficulty: 'thông hiểu', question: 'Nhận định nào đúng về nấm trong đời sống?', options: { A: 'Có loại nấm có ích, cũng có loại nấm gây hại hoặc gây ngộ độc', B: 'Mọi loại nấm đều ăn được', C: 'Nấm chỉ sống ở nơi khô ráo, nhiều nắng', D: 'Nấm không liên quan gì đến thực phẩm' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Dinh dưỡng hợp lí', source_unit: 'Con người và sức khoẻ', source_lesson: 'Dinh dưỡng và thức ăn', skill_tag: ['health', 'application'], difficulty: 'vận dụng', question: 'Bữa sáng nào phù hợp hơn với học sinh tiểu học trước giờ đến lớp?', options: { A: 'Bữa ăn đủ năng lượng, vệ sinh và không quá qua loa', B: 'Chỉ uống nước ngọt rồi đi học', C: 'Bỏ bữa sáng, chờ ăn quà vặt ở cổng trường', D: 'Chỉ ăn một món nhiều dầu mỡ mỗi ngày' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Phòng tránh đuối nước', source_unit: 'Con người và sức khoẻ', source_lesson: 'Phòng tránh đuối nước', skill_tag: ['safety', 'reasoning'], difficulty: 'vận dụng', question: 'Tại sao học sinh không nên xuống ao hồ chơi dù thấy nước nông?', options: { A: 'Vì vẫn có nguy cơ trơn trượt, hố sâu hoặc tai nạn bất ngờ', B: 'Vì nước nông luôn nóng hơn nước sâu', C: 'Vì ao hồ chỉ nguy hiểm vào buổi tối', D: 'Vì nơi có nước nông thì không có cá' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Vệ sinh phòng bệnh', source_unit: 'Con người và sức khoẻ', source_lesson: 'Phòng bệnh liên quan vệ sinh cá nhân', skill_tag: ['health', 'prevention'], difficulty: 'vận dụng', question: 'Thói quen nào giúp hạn chế bệnh lây qua đường tiêu hoá?', options: { A: 'Ăn chín, uống sôi và rửa tay sạch trước khi ăn', B: 'Ăn hoa quả chưa rửa vì nhìn vẫn sạch', C: 'Dùng chung khăn mặt với nhiều người', D: 'Chỉ che thức ăn khi có khách đến nhà' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Môi trường sống của sinh vật', source_unit: 'Sinh vật và môi trường', source_lesson: 'Môi trường sống', skill_tag: ['environment', 'reasoning'], difficulty: 'thông hiểu', question: 'Nếu môi trường sống bị thay đổi xấu đi kéo dài, sinh vật thường gặp khó khăn gì?', options: { A: 'Khó tìm thức ăn, nơi ở và có thể giảm số lượng', B: 'Chắc chắn sinh trưởng tốt hơn vì phải thích nghi', C: 'Không bị ảnh hưởng vì sinh vật tự tạo được môi trường mới ngay', D: 'Chỉ con người mới cần môi trường sống phù hợp' }, correct_answer: 'A' }),
  match(kh4, { topic: 'Ghép nguồn năng lượng với ví dụ', source_unit: 'Năng lượng', source_lesson: 'Âm thanh, ánh sáng, nhiệt', skill_tag: ['energy', 'matching'], difficulty: 'vận dụng', question: 'Ghép hiện tượng với dạng năng lượng nổi bật nhất.', items: [ { label: 'Đèn pin chiếu sáng', correct_match: 'Ánh sáng' }, { label: 'Nước đun sôi làm nóng ấm', correct_match: 'Nhiệt' }, { label: 'Tiếng trống trường', correct_match: 'Âm thanh' } ], option_pool: ['Ánh sáng', 'Nhiệt', 'Âm thanh'] }),
  order(kh4, { topic: 'Chăm sóc cây trồng lớp học', source_unit: 'Thực vật và động vật', source_lesson: 'Nhu cầu sống của thực vật', skill_tag: ['biology', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp công việc chăm sóc cây hợp lí.', items: [ { label: 'Quan sát tình trạng cây và đất', correct_position: 1 }, { label: 'Tưới lượng nước phù hợp, đặt cây nơi đủ sáng', correct_position: 2 }, { label: 'Theo dõi sự thay đổi của cây sau đó', correct_position: 3 } ] }),
  q(kh4, { topic: 'An toàn khi dùng nguồn sáng', source_unit: 'Năng lượng', source_lesson: 'Ánh sáng trong cuộc sống', skill_tag: ['safety', 'application'], difficulty: 'vận dụng', question: 'Việc nào là đúng khi sử dụng đèn học ở nhà?', options: { A: 'Đặt đèn đủ sáng, chiếu phù hợp để bảo vệ mắt', B: 'Ngồi học nơi quá tối cho đỡ chói', C: 'Chiếu đèn thẳng vào mắt để nhìn rõ hơn', D: 'Để đèn quá gần giấy tới mức nóng lên' }, correct_answer: 'A' }),
  q(kh4, { topic: 'Bảo vệ nguồn nước', source_unit: 'Chất', source_lesson: 'Bảo vệ nguồn nước', skill_tag: ['environment', 'application'], difficulty: 'vận dụng', question: 'Việc nào giúp bảo vệ nguồn nước ở khu dân cư?', options: { A: 'Không xả rác và nước bẩn trực tiếp xuống ao hồ, kênh rạch', B: 'Đổ dầu mỡ thừa xuống cống cho trôi đi', C: 'Rửa xe ngay bên mép ao cho tiện', D: 'Đem pin hỏng ném xuống mương' }, correct_answer: 'A' }),

  q(kh5, { topic: 'Bảo vệ đất', source_unit: 'Chất', source_lesson: 'Đất và bảo vệ đất', skill_tag: ['environment', 'application'], difficulty: 'vận dụng', question: 'Biện pháp nào giúp hạn chế xói mòn đất ở vùng đồi núi?', options: { A: 'Trồng cây phủ xanh và giữ rừng', B: 'Chặt cây trên sườn dốc để đất thoáng hơn', C: 'Đốt thực bì thường xuyên vào mùa khô', D: 'Để đất trống sau mưa lớn' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Hỗn hợp và dung dịch', source_unit: 'Chất', source_lesson: 'Hỗn hợp và dung dịch', skill_tag: ['matter', 'application'], difficulty: 'vận dụng', question: 'Muốn tách cát ra khỏi nước đục, cách làm phù hợp hơn cả là:', options: { A: 'Lọc hoặc để lắng rồi gạn', B: 'Dùng nam châm hút', C: 'Thổi mạnh vào cốc nước', D: 'Cho thêm đường để cát biến mất' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Sự biến đổi của chất', source_unit: 'Chất', source_lesson: 'Biến đổi lí học và hoá học', skill_tag: ['matter', 'reasoning'], difficulty: 'thông hiểu', question: 'Hiện tượng nào là biến đổi hoá học?', options: { A: 'Sắt bị gỉ', B: 'Nước đá tan thành nước', C: 'Đường hoà tan trong nước', D: 'Giấy bị xé nhỏ' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Sử dụng năng lượng tiết kiệm', source_unit: 'Năng lượng', source_lesson: 'Sử dụng năng lượng tiết kiệm', skill_tag: ['energy', 'behavior'], difficulty: 'vận dụng', question: 'Việc làm nào thể hiện sử dụng năng lượng tiết kiệm, hiệu quả?', options: { A: 'Tắt quạt, đèn khi không sử dụng', B: 'Bật đèn cả ban ngày cho sáng hơn', C: 'Mở tủ lạnh thật lâu mỗi lần lấy đồ', D: 'Cắm sạc điện suốt ngày dù không dùng' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Mạch điện đơn giản', source_unit: 'Năng lượng', source_lesson: 'Mạch điện đơn giản', skill_tag: ['electricity', 'reasoning'], difficulty: 'vận dụng', question: 'Muốn bóng đèn pin sáng, điều kiện nào cần được đảm bảo?', options: { A: 'Nguồn điện, dây dẫn và bóng đèn được nối thành mạch kín', B: 'Chỉ cần có bóng đèn và công tắc', C: 'Mạch điện càng hở càng sáng', D: 'Không cần pin nếu dây đủ dài' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Vật dẫn điện và cách điện', source_unit: 'Năng lượng', source_lesson: 'Vật dẫn điện và vật cách điện', skill_tag: ['electricity', 'classification'], difficulty: 'thông hiểu', question: 'Vật liệu nào thường được dùng làm vỏ bọc dây điện vì cách điện tốt hơn?', options: { A: 'Nhựa', B: 'Đồng', C: 'Nhôm', D: 'Sắt' }, correct_answer: 'A' }),
  q(kh5, { topic: 'An toàn điện trong gia đình', source_unit: 'Năng lượng', source_lesson: 'An toàn khi sử dụng điện', skill_tag: ['safety', 'electricity'], difficulty: 'vận dụng', question: 'Khi tay còn ướt, em không nên chạm vào công tắc điện vì:', options: { A: 'Nước có thể làm tăng nguy cơ bị điện giật', B: 'Công tắc sẽ đổi màu ngay lập tức', C: 'Điện chỉ nguy hiểm với người lớn', D: 'Tay ướt giúp tắt điện nhanh hơn' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Sinh sản của thực vật', source_unit: 'Thực vật và động vật', source_lesson: 'Sinh sản ở thực vật', skill_tag: ['biology', 'comparison'], difficulty: 'vận dụng', question: 'Ví dụ nào thuộc sinh sản sinh dưỡng ở thực vật?', options: { A: 'Trồng khoai lang bằng dây', B: 'Gieo hạt đỗ để mọc cây mới', C: 'Thụ phấn cho hoa bí tạo quả', D: 'Để hạt thóc trong lọ kín' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Vòng đời động vật', source_unit: 'Thực vật và động vật', source_lesson: 'Sinh sản và phát triển ở động vật', skill_tag: ['biology', 'reasoning'], difficulty: 'thông hiểu', question: 'Việc tìm hiểu vòng đời của côn trùng có ích gì trong thực tế?', options: { A: 'Giúp chăm sóc hoặc phòng trừ đúng thời điểm', B: 'Chỉ để vẽ cho đẹp, không có ý nghĩa gì', C: 'Không liên quan đến sản xuất và đời sống', D: 'Giúp côn trùng lớn nhanh hơn' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Tuổi dậy thì', source_unit: 'Con người và sức khoẻ', source_lesson: 'Sự lớn lên và phát triển của cơ thể', skill_tag: ['health', 'reasoning'], difficulty: 'thông hiểu', question: 'Khi cơ thể bước vào tuổi dậy thì, điều quan trọng học sinh cần làm là:', options: { A: 'Giữ vệ sinh cơ thể, ăn uống lành mạnh và trao đổi với người lớn khi cần', B: 'Lo lắng và giấu kín mọi thay đổi của bản thân', C: 'Tin vào mọi lời truyền miệng chưa kiểm chứng', D: 'Bỏ qua hoàn toàn việc chăm sóc sức khoẻ' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Vi khuẩn và bệnh truyền nhiễm', source_unit: 'Vi khuẩn', source_lesson: 'Vi khuẩn có lợi, có hại và phòng bệnh', skill_tag: ['health', 'prevention'], difficulty: 'vận dụng', question: 'Cách nào giúp hạn chế lây truyền một số bệnh nhiễm khuẩn trong sinh hoạt hằng ngày?', options: { A: 'Giữ vệ sinh, che miệng khi ho và không dùng chung đồ cá nhân khi cần', B: 'Chỉ cần thấy khoẻ là không cần rửa tay', C: 'Để thức ăn chín cạnh rác hữu cơ', D: 'Dùng chung khăn mặt với người đang ốm' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Bảo quản thực phẩm', source_unit: 'Vi khuẩn', source_lesson: 'Vi khuẩn trong chế biến và bảo quản thực phẩm', skill_tag: ['science-life', 'application'], difficulty: 'vận dụng', question: 'Thực phẩm chín nên được che đậy và bảo quản đúng cách chủ yếu để:', options: { A: 'Hạn chế vi khuẩn, ruồi muỗi và bụi bẩn xâm nhập', B: 'Làm thức ăn tự ngọt hơn', C: 'Thực phẩm đổi màu cho đẹp mắt', D: 'Không cần rửa dụng cụ nữa' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Ô nhiễm môi trường nước', source_unit: 'Sinh vật và môi trường', source_lesson: 'Môi trường và tài nguyên', skill_tag: ['environment', 'systems'], difficulty: 'vận dụng', question: 'Nếu một con kênh bị đổ nhiều rác và nước thải lâu ngày, hậu quả nào dễ thấy trước tiên?', options: { A: 'Nước bốc mùi, sinh vật sống trong nước bị ảnh hưởng', B: 'Nước trong hơn do có nhiều chất mới', C: 'Cá và tôm sẽ kéo đến nhiều hơn', D: 'Môi trường xung quanh mát hơn rõ rệt' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Tài nguyên thiên nhiên', source_unit: 'Sinh vật và môi trường', source_lesson: 'Sử dụng hợp lí tài nguyên', skill_tag: ['environment', 'reasoning'], difficulty: 'thông hiểu', question: 'Vì sao cần sử dụng tiết kiệm tài nguyên thiên nhiên?', options: { A: 'Vì nhiều tài nguyên có hạn và cần cho hiện tại lẫn tương lai', B: 'Vì tài nguyên luôn tự sinh ra vô tận mỗi ngày', C: 'Vì tiết kiệm tài nguyên sẽ làm con người không cần sản xuất nữa', D: 'Vì tài nguyên chỉ có ích trong bảo tàng' }, correct_answer: 'A' }),
  match(kh5, { topic: 'Ghép hành động với mục tiêu bảo vệ môi trường', source_unit: 'Sinh vật và môi trường', source_lesson: 'Bảo vệ môi trường', skill_tag: ['environment', 'matching'], difficulty: 'vận dụng', question: 'Ghép hành động với mục tiêu phù hợp.', items: [ { label: 'Trồng cây', correct_match: 'Giữ đất, làm môi trường xanh hơn' }, { label: 'Phân loại rác', correct_match: 'Tạo thuận lợi cho thu gom và xử lí' }, { label: 'Tiết kiệm điện', correct_match: 'Giảm lãng phí năng lượng' } ], option_pool: ['Giữ đất, làm môi trường xanh hơn', 'Tạo thuận lợi cho thu gom và xử lí', 'Giảm lãng phí năng lượng'] }),
  order(kh5, { topic: 'Xử lí khi phát hiện dây điện hở', source_unit: 'Năng lượng', source_lesson: 'An toàn điện', skill_tag: ['safety', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp cách xử lí phù hợp khi thấy dây điện hở ngoài sân.', items: [ { label: 'Tránh xa khu vực nguy hiểm', correct_position: 1 }, { label: 'Báo cho người lớn hoặc người có trách nhiệm', correct_position: 2 }, { label: 'Chờ xử lí, không tự ý chạm vào', correct_position: 3 } ] }),
  q(kh5, { topic: 'Nguồn năng lượng tái tạo', source_unit: 'Năng lượng', source_lesson: 'Một số nguồn năng lượng', skill_tag: ['energy', 'classification'], difficulty: 'thông hiểu', question: 'Nguồn năng lượng nào được xếp vào nhóm tái tạo?', options: { A: 'Năng lượng mặt trời', B: 'Than đá', C: 'Dầu mỏ', D: 'Khí thiên nhiên' }, correct_answer: 'A' }),
  q(kh5, { topic: 'Thói quen bảo vệ sức khoẻ', source_unit: 'Con người và sức khoẻ', source_lesson: 'Chăm sóc sức khoẻ tuổi dậy thì', skill_tag: ['health', 'application'], difficulty: 'vận dụng', question: 'Bạn nào có thói quen tốt hơn cho sức khoẻ lâu dài?', options: { A: 'Ngủ đủ, vận động hợp lí và ăn uống cân đối', B: 'Thức khuya thường xuyên để chơi điện tử', C: 'Bỏ bữa sáng nhưng uống nước ngọt nhiều', D: 'Ngại vận động vì sợ mệt' }, correct_answer: 'A' })
];
