const q = (base, extra) => ({ ...base, type: 'single_choice', ...extra });
const match = (base, extra) => ({ ...base, type: 'matching', ...extra });
const order = (base, extra) => ({ ...base, type: 'ordering', ...extra });

const tnxh3 = {
  grade: 3,
  book: 'Tự nhiên và Xã hội 3 - Kết nối tri thức',
  subject: 'Tự nhiên và Xã hội'
};

const lsdl4 = {
  grade: 4,
  book: 'Lịch sử và Địa lí 4 - Kết nối tri thức',
  subject: 'Lịch sử và Địa lí'
};

const lsdl5 = {
  grade: 5,
  book: 'Lịch sử và Địa lí 5 - Kết nối tri thức',
  subject: 'Lịch sử và Địa lí'
};

module.exports = [
  q(tnxh3, { topic: 'Ngày kỉ niệm của gia đình', source_unit: 'Gia đình', source_lesson: 'Họ hàng và những ngày kỉ niệm của gia đình', skill_tag: ['family', 'application'], difficulty: 'vận dụng', question: 'Trong ngày sinh nhật của ông, việc làm nào thể hiện sự quan tâm phù hợp nhất của học sinh lớp 3?', options: { A: 'Chuẩn bị lời chúc và giúp việc vừa sức theo khả năng', B: 'Tự ý mời thật nhiều khách mà không hỏi người lớn', C: 'Đòi quà trước rồi mới chúc mừng', D: 'Bỏ sang nhà bạn chơi vì nghĩ người lớn tự lo được' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Sắp xếp công việc khi có cháy', source_unit: 'Gia đình', source_lesson: 'Phòng tránh hoả hoạn khi ở nhà', skill_tag: ['safety', 'sequence'], difficulty: 'vận dụng', question: 'Khi phát hiện khói bốc ra từ ổ điện, em nên ưu tiên cách xử lí nào?', options: { A: 'Báo người lớn, tránh xa nơi nguy hiểm và tìm cách ra chỗ an toàn', B: 'Lấy tay rút dây điện ngay cho nhanh', C: 'Đứng lại quan sát xem khói có tự hết không', D: 'Đổ nước vào ổ điện để dập ngay' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Giữ vệ sinh trường học', source_unit: 'Trường học', source_lesson: 'Giữ vệ sinh trường học', skill_tag: ['community', 'behavior'], difficulty: 'thông hiểu', question: 'Việc nào góp phần giữ vệ sinh trường học bền vững hơn cả?', options: { A: 'Bỏ rác đúng nơi quy định và nhắc bạn cùng thực hiện', B: 'Chỉ dọn sạch chỗ của mình còn sân trường để cô lao công lo', C: 'Đợi đến cuối tuần mới gom rác một lần', D: 'Thấy rác ít nên có thể bỏ tạm dưới gầm bàn' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Truyền thống nhà trường', source_unit: 'Trường học', source_lesson: 'Truyền thống nhà trường', skill_tag: ['school', 'respect'], difficulty: 'vận dụng', question: 'Cách tìm hiểu truyền thống nhà trường nào phù hợp và đáng tin cậy nhất?', options: { A: 'Nghe thầy cô giới thiệu, xem bảng truyền thống và tư liệu của trường', B: 'Tự đoán theo lời kể vui của bạn trong lớp', C: 'Chỉ nhìn màu sơn cổng trường để suy ra lịch sử', D: 'Nghe một người lạ trước cổng trường rồi ghi lại' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'An toàn khi mua bán', source_unit: 'Cộng đồng địa phương', source_lesson: 'Hoạt động mua bán hàng hoá', skill_tag: ['application', 'community'], difficulty: 'vận dụng', question: 'Khi đi chợ cùng mẹ, việc làm nào thể hiện thói quen mua bán văn minh?', options: { A: 'Xếp hàng, giữ trật tự và nhận hàng đúng phần của mình', B: 'Chen lên trước vì nghĩ mua ít được ưu tiên', C: 'Tự ý bóc hàng ăn thử rồi bỏ lại', D: 'Vứt cuống rau xuống nền chợ cho tiện' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Nghề nghiệp địa phương', source_unit: 'Cộng đồng địa phương', source_lesson: 'Một số hoạt động sản xuất ở địa phương', skill_tag: ['production', 'classification'], difficulty: 'vận dụng', question: 'Đặc điểm nào thường gặp ở nghề làm nón, đan lát, làm gốm ở địa phương?', options: { A: 'Sản phẩm thường gắn với sự khéo léo của người thợ và có thể làm theo lô nhỏ', B: 'Chỉ tạo ra sản phẩm bằng dây chuyền rô-bốt tự động hoàn toàn', C: 'Chỉ xuất hiện ở những nơi có mỏ than lớn', D: 'Không cần nguyên liệu và dụng cụ lao động' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Chăm sóc cây trồng', source_unit: 'Thực vật và động vật', source_lesson: 'Chăm sóc và bảo vệ cây trồng', skill_tag: ['biology', 'application'], difficulty: 'vận dụng', question: 'Nếu cây lớp em trồng có lá héo rũ sau nhiều ngày nắng gắt, nguyên nhân dễ nghĩ đến trước nhất là gì?', options: { A: 'Cây thiếu nước và cần được chăm sóc phù hợp', B: 'Cây nhận quá nhiều tiếng nói của học sinh', C: 'Cây héo vì có quá nhiều bóng râm', D: 'Cây nào cũng phải héo vào buổi trưa dù đủ nước' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Điều kiện sống của động vật', source_unit: 'Thực vật và động vật', source_lesson: 'Nhu cầu sống của động vật', skill_tag: ['biology', 'inference'], difficulty: 'thông hiểu', question: 'Nếu bể cá lâu ngày không được thay nước và cho ăn đúng cách, điều gì dễ xảy ra nhất?', options: { A: 'Cá yếu đi vì môi trường sống không còn phù hợp', B: 'Cá sẽ tự tìm đường ra ao hồ khác', C: 'Cá lớn nhanh hơn vì nước đục giữ ấm tốt', D: 'Cá không bị ảnh hưởng vì chỉ cần có bể kính' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Phân biệt thân, rễ, lá', source_unit: 'Thực vật và động vật', source_lesson: 'Một số bộ phận của thực vật', skill_tag: ['classification', 'biology'], difficulty: 'vận dụng', question: 'Bộ phận nào của cây thường có nhiệm vụ hút nước và chất khoáng từ đất?', options: { A: 'Rễ', B: 'Hoa', C: 'Quả', D: 'Hạt' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Chăm sóc cơ thể', source_unit: 'Con người và sức khoẻ', source_lesson: 'Vệ sinh cơ thể và phòng bệnh', skill_tag: ['health', 'application'], difficulty: 'vận dụng', question: 'Thói quen nào giúp hạn chế bệnh đường tiêu hoá cho học sinh tiểu học?', options: { A: 'Rửa tay trước khi ăn và sau khi đi vệ sinh', B: 'Ăn nhanh đồ nguội để tiết kiệm thời gian', C: 'Dùng chung cốc uống nước với nhiều bạn', D: 'Chỉ rửa tay khi tay nhìn thấy bẩn rõ' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Luyện tập và nghỉ ngơi', source_unit: 'Con người và sức khoẻ', source_lesson: 'Hoạt động nghỉ ngơi và vui chơi', skill_tag: ['health', 'reasoning'], difficulty: 'thông hiểu', question: 'Vì sao học sinh không nên vừa ăn xong đã chạy nhảy mạnh liên tục?', options: { A: 'Cơ thể cần thời gian tiêu hoá thức ăn', B: 'Vì chạy chỉ dành cho buổi tối', C: 'Vì sau ăn xong cơ thể không cần vận động nữa', D: 'Vì vận động làm thức ăn biến mất hoàn toàn' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Mặt Trời và phương hướng', source_unit: 'Trái Đất và bầu trời', source_lesson: 'Mặt Trời và phương hướng', skill_tag: ['astronomy', 'application'], difficulty: 'vận dụng', question: 'Buổi sáng, nếu em đứng quay mặt về phía Mặt Trời mọc, phía tay trái em thường là hướng nào?', options: { A: 'Bắc', B: 'Nam', C: 'Tây', D: 'Đông' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Ngày và đêm', source_unit: 'Trái Đất và bầu trời', source_lesson: 'Ngày và đêm', skill_tag: ['astronomy', 'reasoning'], difficulty: 'thông hiểu', question: 'Hiện tượng ngày và đêm lặp lại có liên quan trực tiếp nhất đến điều nào?', options: { A: 'Trái Đất tự quay quanh mình', B: 'Mặt Trăng che khuất Mặt Trời mỗi tối', C: 'Các ngôi sao thay nhau toả sáng', D: 'Mây di chuyển quanh bầu trời' }, correct_answer: 'A' }),
  match(tnxh3, { topic: 'Nơi sống của sinh vật', source_unit: 'Thực vật và động vật', source_lesson: 'Nơi sống của động vật', skill_tag: ['biology', 'matching'], difficulty: 'vận dụng', question: 'Ghép con vật với nơi sống phù hợp nhất.', items: [ { label: 'Cá rô', correct_match: 'Ao, hồ' }, { label: 'Gà', correct_match: 'Chuồng, sân vườn' }, { label: 'Ong', correct_match: 'Tổ trên cây hoặc mái hiên' } ], option_pool: ['Ao, hồ', 'Chuồng, sân vườn', 'Tổ trên cây hoặc mái hiên'] }),
  order(tnxh3, { topic: 'Rửa tay đúng cách', source_unit: 'Con người và sức khoẻ', source_lesson: 'Vệ sinh cơ thể', skill_tag: ['health', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp theo thứ tự hợp lí các việc sau khi rửa tay.', items: [ { label: 'Làm ướt tay và lấy xà phòng', correct_position: 1 }, { label: 'Chà sạch lòng bàn tay, kẽ ngón tay', correct_position: 2 }, { label: 'Xả sạch dưới vòi nước và lau khô', correct_position: 3 } ] }),
  q(tnxh3, { topic: 'Chăm sóc vật nuôi', source_unit: 'Thực vật và động vật', source_lesson: 'Chăm sóc và bảo vệ vật nuôi', skill_tag: ['biology', 'behavior'], difficulty: 'vận dụng', question: 'Khi chơi với chó mèo trong nhà, việc nào an toàn và đúng cách hơn cả?', options: { A: 'Không chọc phá, rửa tay sau khi chơi và nhờ người lớn hỗ trợ khi cần', B: 'Ôm ghì vật nuôi khi chúng đang ăn', C: 'Kéo đuôi để thử phản ứng của chúng', D: 'Cho vật nuôi ăn bất cứ thứ gì mình thích' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Bầu trời ban đêm', source_unit: 'Trái Đất và bầu trời', source_lesson: 'Bầu trời ban đêm', skill_tag: ['astronomy', 'observation'], difficulty: 'thông hiểu', question: 'Đặc điểm nào thường đúng khi quan sát bầu trời ban đêm?', options: { A: 'Có thể nhìn thấy Mặt Trăng và nhiều ngôi sao khi trời quang', B: 'Mặt Trời xuất hiện sáng rõ như ban ngày', C: 'Mọi đám mây đều biến mất hoàn toàn', D: 'Các vì sao đứng yên nên không thay đổi vị trí biểu kiến' }, correct_answer: 'A' }),
  q(tnxh3, { topic: 'Bảo vệ môi trường xung quanh', source_unit: 'Cộng đồng địa phương', source_lesson: 'Bảo vệ môi trường nơi em sống', skill_tag: ['environment', 'application'], difficulty: 'vận dụng', question: 'Nếu lớp em tổ chức dọn vệ sinh khu vực cổng trường, việc nào là hợp lí nhất?', options: { A: 'Phân công công việc, mang dụng cụ phù hợp và bỏ rác đúng nơi quy định', B: 'Gom rác lại rồi để ngay cạnh cổng cho tiện', C: 'Đốt lá và túi nhựa chung một chỗ để nhanh sạch', D: 'Chỉ chụp ảnh hoạt động mà không tham gia dọn' }, correct_answer: 'A' }),

  q(lsdl4, { topic: 'Đọc phương hướng trên bản đồ', source_unit: 'Mở đầu', source_lesson: 'Làm quen với phương tiện học tập môn Lịch sử và Địa lí', skill_tag: ['map-reading', 'application'], difficulty: 'vận dụng', question: 'Khi xem bản đồ có mũi tên chỉ hướng Bắc, khu vực bên phải bản đồ thường là hướng nào?', options: { A: 'Đông', B: 'Tây', C: 'Nam', D: 'Bắc' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Sử dụng kí hiệu bản đồ', source_unit: 'Mở đầu', source_lesson: 'Làm quen với phương tiện học tập môn Lịch sử và Địa lí', skill_tag: ['map-reading', 'reasoning'], difficulty: 'thông hiểu', question: 'Muốn hiểu các hình vẽ nhỏ trên bản đồ thể hiện điều gì, em cần chú ý nhất đến phần nào?', options: { A: 'Bảng chú giải', B: 'Tên người vẽ bản đồ', C: 'Màu giấy in bản đồ', D: 'Khung viền ngoài bản đồ' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Nguồn tư liệu lịch sử', source_unit: 'Địa phương em', source_lesson: 'Lịch sử và văn hoá truyền thống địa phương em', skill_tag: ['history', 'application'], difficulty: 'vận dụng', question: 'Để biết chính xác ngôi đình cổ ở địa phương được xây từ thời nào, cách làm nào hợp lí nhất?', options: { A: 'Đối chiếu tư liệu, hỏi người hướng dẫn và xem thông tin chính thức tại di tích', B: 'Chọn năm bất kì theo cảm nhận của mình', C: 'Nghe kể miệng một lần rồi khẳng định ngay', D: 'Chỉ xem ảnh trên mạng mà không kiểm tra nguồn' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Trung du và miền núi Bắc Bộ', source_unit: 'Trung du và miền núi Bắc Bộ', source_lesson: 'Thiên nhiên và hoạt động sản xuất', skill_tag: ['region', 'comparison'], difficulty: 'vận dụng', question: 'Điều kiện nào góp phần làm vùng trung du và miền núi Bắc Bộ phát triển cây chè ở nhiều nơi?', options: { A: 'Địa hình đồi núi và khí hậu phù hợp ở nhiều khu vực', B: 'Có nhiều bãi biển cát trắng kéo dài', C: 'Sông ngòi ít nên cây công nghiệp phát triển hơn', D: 'Đồng bằng rộng lớn bằng phẳng chiếm chủ yếu' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Đồng bằng Bắc Bộ', source_unit: 'Đồng bằng Bắc Bộ', source_lesson: 'Đê điều và sản xuất', skill_tag: ['region', 'cause-effect'], difficulty: 'thông hiểu', question: 'Hệ thống đê ở Đồng bằng Bắc Bộ có vai trò nổi bật nào?', options: { A: 'Giúp hạn chế tác hại của lũ và bảo vệ sản xuất, đời sống', B: 'Giúp biển lùi xa hoàn toàn khỏi đất liền', C: 'Làm cho mọi con sông ngừng chảy', D: 'Thay thế hoàn toàn cho hệ thống đường giao thông' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Thăng Long - Hà Nội', source_unit: 'Đồng bằng Bắc Bộ', source_lesson: 'Thăng Long - Hà Nội', skill_tag: ['history', 'urban-history'], difficulty: 'vận dụng', question: 'Ý nào thể hiện đúng vai trò của Hà Nội trong hiện tại?', options: { A: 'Là trung tâm chính trị, văn hoá và có nhiều giá trị lịch sử tiêu biểu', B: 'Chỉ là nơi lưu giữ di tích, không có vai trò phát triển hiện nay', C: 'Là thành phố duy nhất của đồng bằng Bắc Bộ', D: 'Không có hoạt động giáo dục và khoa học' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Duyên hải miền Trung', source_unit: 'Duyên hải miền Trung', source_lesson: 'Thiên nhiên miền Trung', skill_tag: ['region', 'reasoning'], difficulty: 'vận dụng', question: 'Vì sao nhiều tỉnh duyên hải miền Trung vừa phát triển đánh bắt, nuôi trồng thuỷ sản vừa cần chú ý phòng chống thiên tai?', options: { A: 'Vì vùng giáp biển, giàu tiềm năng biển nhưng thường chịu bão và mưa lớn', B: 'Vì vùng này quanh năm băng tuyết dày', C: 'Vì hầu như không có sông và đầm phá', D: 'Vì người dân chỉ sống bằng nghề rừng' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Tây Nguyên', source_unit: 'Tây Nguyên', source_lesson: 'Đất đỏ ba dan và sản xuất', skill_tag: ['region', 'application'], difficulty: 'vận dụng', question: 'Cây trồng nào thường gắn nhiều với vùng Tây Nguyên hơn cả?', options: { A: 'Cà phê', B: 'Lúa nước trên đồng bằng châu thổ rộng lớn', C: 'Dừa nước ở vùng ngập mặn', D: 'Cói trồng ven biển' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Nam Bộ', source_unit: 'Nam Bộ', source_lesson: 'Sông ngòi và hoạt động sản xuất', skill_tag: ['region', 'application'], difficulty: 'vận dụng', question: 'Đặc điểm nào thường thấy ở nhiều nơi thuộc Nam Bộ?', options: { A: 'Mạng lưới sông ngòi, kênh rạch khá dày', B: 'Địa hình núi cao hiểm trở chiếm chủ yếu', C: 'Khí hậu lạnh giá quanh năm', D: 'Ruộng bậc thang là kiểu canh tác phổ biến nhất' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'So sánh các vùng', source_unit: 'Nhiều vùng', source_lesson: 'Các bài về vùng miền', skill_tag: ['comparison', 'region'], difficulty: 'vận dụng', question: 'Nhận xét nào hợp lí khi so sánh Đồng bằng Bắc Bộ và Tây Nguyên?', options: { A: 'Một bên nổi bật đồng bằng châu thổ, một bên nổi bật cao nguyên', B: 'Cả hai đều chủ yếu là vùng biển đảo', C: 'Cả hai đều không có hoạt động nông nghiệp', D: 'Tây Nguyên là vùng đồng bằng thấp rộng hơn Bắc Bộ' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Bảo tồn di tích', source_unit: 'Địa phương em', source_lesson: 'Di sản ở địa phương', skill_tag: ['heritage', 'behavior'], difficulty: 'vận dụng', question: 'Việc nào vừa giúp tìm hiểu di tích vừa thể hiện sự tôn trọng?', options: { A: 'Ghi chép, chụp ảnh đúng nơi cho phép và giữ gìn hiện vật', B: 'Sờ tay liên tục vào đồ cổ để nhớ lâu hơn', C: 'Tự ý mang theo một mảnh gốm nhỏ làm kỉ niệm', D: 'Nói to và chạy nhảy trong khu thờ tự' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Vai trò sông ngòi', source_unit: 'Đồng bằng Bắc Bộ; Nam Bộ', source_lesson: 'Các bài về sông ngòi', skill_tag: ['cause-effect', 'region'], difficulty: 'thông hiểu', question: 'Sông ngòi có ý nghĩa lớn đối với sản xuất nông nghiệp chủ yếu vì:', options: { A: 'Cung cấp nước, phù sa và thuận lợi cho giao thông ở nhiều nơi', B: 'Làm cho mọi vùng có khí hậu giống hệt nhau', C: 'Ngăn hoàn toàn thiên tai xảy ra', D: 'Chỉ dùng để trang trí cảnh quan' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Lễ hội truyền thống', source_unit: 'Địa phương em', source_lesson: 'Văn hoá truyền thống địa phương', skill_tag: ['culture', 'application'], difficulty: 'vận dụng', question: 'Khi tham gia lễ hội truyền thống ở địa phương, học sinh nên ứng xử thế nào?', options: { A: 'Ăn mặc gọn gàng, giữ trật tự và tìm hiểu ý nghĩa lễ hội', B: 'Chen lấn để đứng gần nơi hành lễ nhất', C: 'Đùa nghịch ở khu vực linh thiêng cho vui', D: 'Xả rác vì nghĩ đã có người dọn' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Đọc trục thời gian', source_unit: 'Mở đầu', source_lesson: 'Phương tiện học tập', skill_tag: ['history', 'tool-choice'], difficulty: 'vận dụng', question: 'Nếu một sự kiện nằm bên trái sự kiện khác trên cùng trục thời gian, điều đó thường cho biết:', options: { A: 'Sự kiện đó xảy ra sớm hơn', B: 'Sự kiện đó xảy ra ở phía tây hơn', C: 'Sự kiện đó quan trọng hơn hẳn', D: 'Sự kiện đó luôn kéo dài hơn' }, correct_answer: 'A' }),
  order(lsdl4, { topic: 'Quy trình tìm hiểu địa phương', source_unit: 'Địa phương em', source_lesson: 'Tìm hiểu lịch sử và văn hoá địa phương', skill_tag: ['application', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp các việc sau để tìm hiểu một di tích ở địa phương.', items: [ { label: 'Xác định di tích cần tìm hiểu', correct_position: 1 }, { label: 'Thu thập thông tin từ nguồn đáng tin cậy', correct_position: 2 }, { label: 'Ghi chép, trình bày kết quả', correct_position: 3 } ] }),
  match(lsdl4, { topic: 'Ghép vùng với đặc điểm', source_unit: 'Các vùng miền', source_lesson: 'Bài về các vùng', skill_tag: ['region', 'matching'], difficulty: 'vận dụng', question: 'Ghép vùng với đặc điểm tiêu biểu nhất.', items: [ { label: 'Tây Nguyên', correct_match: 'Cao nguyên và cây công nghiệp lâu năm' }, { label: 'Đồng bằng Bắc Bộ', correct_match: 'Châu thổ rộng, có hệ thống đê' }, { label: 'Nam Bộ', correct_match: 'Kênh rạch khá dày ở nhiều nơi' } ], option_pool: ['Cao nguyên và cây công nghiệp lâu năm', 'Châu thổ rộng, có hệ thống đê', 'Kênh rạch khá dày ở nhiều nơi'] }),
  q(lsdl4, { topic: 'Học tập từ bản đồ và tranh ảnh', source_unit: 'Mở đầu', source_lesson: 'Phương tiện học tập', skill_tag: ['map-reading', 'tool-choice'], difficulty: 'vận dụng', question: 'Muốn biết một vùng có nhiều núi hay đồng bằng, em nên ưu tiên xem loại bản đồ nào hơn?', options: { A: 'Bản đồ địa hình', B: 'Trục thời gian', C: 'Bản đồ lễ hội', D: 'Sổ liên lạc' }, correct_answer: 'A' }),
  q(lsdl4, { topic: 'Mối quan hệ giữa thiên nhiên và sản xuất', source_unit: 'Nhiều vùng', source_lesson: 'Các bài về vùng miền', skill_tag: ['cause-effect', 'application'], difficulty: 'vận dụng', question: 'Kết luận nào đúng nhất về mối quan hệ giữa đặc điểm tự nhiên và hoạt động sản xuất ở các vùng?', options: { A: 'Điều kiện tự nhiên khác nhau thường làm cho sản xuất mỗi vùng có nét riêng', B: 'Mọi vùng đều sản xuất giống nhau nên không cần tìm hiểu tự nhiên', C: 'Sản xuất hoàn toàn không phụ thuộc tài nguyên và khí hậu', D: 'Chỉ con người quyết định, thiên nhiên không ảnh hưởng gì' }, correct_answer: 'A' }),

  q(lsdl5, { topic: 'Vị trí lãnh thổ Việt Nam', source_unit: 'Đất nước và con người Việt Nam', source_lesson: 'Vị trí địa lí Việt Nam', skill_tag: ['map-thinking', 'application'], difficulty: 'vận dụng', question: 'Vì sao vị trí địa lí của Việt Nam thuận lợi cho giao lưu kinh tế với nhiều nước?', options: { A: 'Vì nằm ở khu vực Đông Nam Á, gần các tuyến giao thông biển và khu vực phát triển năng động', B: 'Vì nằm tách biệt hoàn toàn khỏi biển và các nước xung quanh', C: 'Vì chỉ tiếp giáp với một quốc gia duy nhất', D: 'Vì lãnh thổ chỉ gồm các đảo nhỏ giữa đại dương' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Biển đảo Việt Nam', source_unit: 'Đất nước và con người Việt Nam', source_lesson: 'Biển, đảo Việt Nam', skill_tag: ['marine', 'application'], difficulty: 'vận dụng', question: 'Ý nào vừa thể hiện giá trị kinh tế vừa thể hiện giá trị chiến lược của biển đảo?', options: { A: 'Biển đảo cung cấp tài nguyên, tạo điều kiện giao thương và gắn với bảo vệ chủ quyền', B: 'Biển đảo chỉ có ý nghĩa du lịch nên ít liên quan đến quốc gia', C: 'Biển đảo càng xa dân cư thì càng không cần quan tâm', D: 'Khai thác biển là việc riêng của ngư dân, không liên quan môi trường' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Các quốc gia cổ trên lãnh thổ Việt Nam', source_unit: 'Những quốc gia đầu tiên trên lãnh thổ Việt Nam', source_lesson: 'Phù Nam, Chăm-pa', skill_tag: ['history', 'comparison'], difficulty: 'thông hiểu', question: 'Việc tìm hiểu các quốc gia cổ giúp học sinh nhận ra điều gì?', options: { A: 'Lịch sử và văn hoá trên lãnh thổ Việt Nam có quá trình hình thành phong phú, đa dạng', B: 'Lãnh thổ nước ta xưa nay chỉ có một cộng đồng duy nhất tồn tại', C: 'Các quốc gia cổ không để lại dấu tích nào cho hiện tại', D: 'Lịch sử Việt Nam chỉ gắn với thời hiện đại' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Khởi nghĩa và chiến thắng trong lịch sử dân tộc', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Các bài về các cuộc kháng chiến', skill_tag: ['history', 'comparison'], difficulty: 'vận dụng', question: 'Điểm chung nổi bật của nhiều chiến thắng lớn trong lịch sử dân tộc là gì?', options: { A: 'Đều thể hiện tinh thần đoàn kết và ý chí bảo vệ đất nước', B: 'Đều diễn ra hoàn toàn trên biển', C: 'Đều kết thúc bằng việc nhân dân rời bỏ quê hương', D: 'Đều không có vai trò của nhân dân' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Bài học từ lịch sử', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Nhiều bài', skill_tag: ['history', 'reasoning'], difficulty: 'vận dụng', question: 'Học về các nhân vật lịch sử tiêu biểu giúp học sinh rút ra điều gì thiết thực nhất?', options: { A: 'Biết trân trọng quá khứ và học những phẩm chất tốt đẹp để vận dụng vào hiện tại', B: 'Chỉ cần nhớ tên nhân vật mà không cần hiểu việc làm', C: 'Lịch sử chỉ có ý nghĩa trong giờ kiểm tra', D: 'Người xưa giỏi nên người nay không cần cố gắng' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Cách mạng tháng Tám và Quốc khánh', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Cách mạng tháng Tám năm 1945', skill_tag: ['history', 'application'], difficulty: 'thông hiểu', question: 'Ngày Quốc khánh 2-9 được ghi nhớ vì gắn với sự kiện nào?', options: { A: 'Nước Việt Nam Dân chủ Cộng hoà ra đời', B: 'Chiến thắng Điện Biên Phủ kết thúc', C: 'Bắt đầu Chiến dịch Hồ Chí Minh', D: 'Hoàn thành công cuộc đổi mới' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Điện Biên Phủ', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Chiến thắng Điện Biên Phủ năm 1954', skill_tag: ['history', 'modern-history'], difficulty: 'vận dụng', question: 'Khi nói Chiến thắng Điện Biên Phủ có ý nghĩa lớn, người ta muốn nhấn mạnh điều gì?', options: { A: 'Đây là thắng lợi quan trọng, cổ vũ mạnh mẽ phong trào giải phóng dân tộc', B: 'Đây chỉ là một trận nhỏ, ít ảnh hưởng', C: 'Đây là sự kiện chỉ có ý nghĩa với riêng một địa phương', D: 'Đây là sự kiện diễn ra sau năm 1975' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Chiến dịch Hồ Chí Minh', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Chiến dịch Hồ Chí Minh năm 1975', skill_tag: ['history', 'modern-history'], difficulty: 'vận dụng', question: 'Ý nghĩa nổi bật của Chiến dịch Hồ Chí Minh là:', options: { A: 'Góp phần giải phóng hoàn toàn miền Nam, thống nhất đất nước', B: 'Mở đầu thời kì Bắc thuộc', C: 'Thiết lập hệ thống đê điều ở đồng bằng Bắc Bộ', D: 'Đánh dấu sự ra đời của nhà nước Văn Lang' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Quan hệ với các nước láng giềng', source_unit: 'Các nước láng giềng', source_lesson: 'Lào, Campuchia, Trung Quốc và ASEAN', skill_tag: ['regional-cooperation', 'application'], difficulty: 'vận dụng', question: 'Trong giao lưu với bạn bè đến từ các nước láng giềng, cách ứng xử nào phù hợp nhất?', options: { A: 'Tôn trọng sự khác biệt và chủ động học hỏi điều hay', B: 'Áp đặt thói quen của mình cho mọi người', C: 'Trêu chọc vì khác ngôn ngữ', D: 'Từ chối tìm hiểu vì nghĩ không cần thiết' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Tìm hiểu thế giới', source_unit: 'Tìm hiểu thế giới', source_lesson: 'Bản đồ thế giới và châu lục', skill_tag: ['map-thinking', 'application'], difficulty: 'vận dụng', question: 'Muốn biết một nước thuộc châu lục nào, em cần tra cứu phù hợp nhất trên:', options: { A: 'Bản đồ thế giới hoặc quả địa cầu', B: 'Trục thời gian lịch sử Việt Nam', C: 'Sổ điểm cá nhân', D: 'Bảng cửu chương' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Chung tay xây dựng thế giới', source_unit: 'Chung tay xây dựng thế giới', source_lesson: 'Bảo vệ môi trường và hợp tác quốc tế', skill_tag: ['global-citizenship', 'behavior'], difficulty: 'vận dụng', question: 'Việc nào thể hiện trách nhiệm của học sinh đối với môi trường sống chung?', options: { A: 'Tiết kiệm điện nước, phân loại rác và tham gia hoạt động xanh', B: 'Dùng nhiều đồ nhựa một lần vì tiện hơn', C: 'Cho rằng bảo vệ môi trường chỉ là việc của nhà máy', D: 'Đốt rác ngoài trời để đỡ tốn công thu gom' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Đặc điểm dân cư và lao động', source_unit: 'Đất nước và con người Việt Nam', source_lesson: 'Dân cư Việt Nam', skill_tag: ['application', 'reasoning'], difficulty: 'thông hiểu', question: 'Việc dân cư phân bố không đều giữa các vùng thường dẫn đến điều gì?', options: { A: 'Nhu cầu phát triển kinh tế - xã hội và tổ chức đời sống ở mỗi vùng có thể khác nhau', B: 'Mọi vùng có số dân và việc làm hoàn toàn giống nhau', C: 'Không ảnh hưởng gì đến học tập và sản xuất', D: 'Khiến mọi đô thị biến mất' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'So sánh sự kiện lịch sử', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Các mốc lịch sử hiện đại', skill_tag: ['comparison', 'history'], difficulty: 'vận dụng', question: 'Khi so sánh Cách mạng tháng Tám 1945 và Chiến dịch Hồ Chí Minh 1975, nhận định nào đúng nhất?', options: { A: 'Cả hai đều là mốc rất quan trọng trong quá trình giành và giữ độc lập dân tộc', B: 'Cả hai đều diễn ra trước năm 1900', C: 'Cả hai đều chỉ tác động tới một tỉnh', D: 'Cả hai đều không liên quan đến việc thống nhất đất nước' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Vai trò của bản đồ hành chính', source_unit: 'Đất nước và con người Việt Nam', source_lesson: 'Bản đồ hành chính Việt Nam', skill_tag: ['map-thinking', 'tool-choice'], difficulty: 'vận dụng', question: 'Muốn biết tỉnh nào giáp biển và tỉnh nào không giáp biển, em nên dùng nguồn nào hiệu quả nhất?', options: { A: 'Bản đồ hành chính kết hợp quan sát vị trí lãnh thổ', B: 'Một bài hát về quê hương', C: 'Lời đoán của bạn cùng lớp', D: 'Bảng điểm môn học' }, correct_answer: 'A' }),
  match(lsdl5, { topic: 'Ghép sự kiện với ý nghĩa', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Một số sự kiện lớn', skill_tag: ['history', 'matching'], difficulty: 'vận dụng', question: 'Ghép sự kiện với ý nghĩa gần đúng nhất.', items: [ { label: 'Cách mạng tháng Tám 1945', correct_match: 'Mở ra nền độc lập mới cho dân tộc' }, { label: 'Điện Biên Phủ 1954', correct_match: 'Thắng lợi lớn trong kháng chiến chống Pháp' }, { label: 'Chiến dịch Hồ Chí Minh 1975', correct_match: 'Giải phóng miền Nam, thống nhất đất nước' } ], option_pool: ['Mở ra nền độc lập mới cho dân tộc', 'Thắng lợi lớn trong kháng chiến chống Pháp', 'Giải phóng miền Nam, thống nhất đất nước'] }),
  order(lsdl5, { topic: 'Các bước tìm hiểu một quốc gia', source_unit: 'Tìm hiểu thế giới', source_lesson: 'Một số quốc gia trên thế giới', skill_tag: ['application', 'ordering'], difficulty: 'vận dụng', question: 'Sắp xếp các việc sau khi tìm hiểu một quốc gia trên thế giới.', items: [ { label: 'Xác định vị trí trên bản đồ', correct_position: 1 }, { label: 'Tìm hiểu đặc điểm tiêu biểu về tự nhiên, con người', correct_position: 2 }, { label: 'So sánh, rút ra điều em học được', correct_position: 3 } ] }),
  q(lsdl5, { topic: 'Biển đảo và môi trường', source_unit: 'Đất nước và con người Việt Nam', source_lesson: 'Biển, đảo Việt Nam', skill_tag: ['marine', 'environment'], difficulty: 'vận dụng', question: 'Nếu rác thải nhựa trôi ra biển ngày càng nhiều, hậu quả dễ thấy nhất là gì?', options: { A: 'Sinh vật biển và môi trường biển bị ảnh hưởng xấu', B: 'Nguồn lợi thuỷ sản tự tăng lên', C: 'Biển sẽ sạch hơn vì có thêm vật nổi', D: 'Không liên quan đến hoạt động của con người' }, correct_answer: 'A' }),
  q(lsdl5, { topic: 'Tinh thần yêu nước', source_unit: 'Xây dựng và bảo vệ đất nước Việt Nam', source_lesson: 'Nhiều bài', skill_tag: ['history', 'citizenship'], difficulty: 'vận dụng', question: 'Biểu hiện nào gần nhất với việc tiếp nối truyền thống yêu nước trong đời sống học sinh hôm nay?', options: { A: 'Chăm học, có trách nhiệm và góp sức xây dựng cộng đồng', B: 'Chỉ thuộc tên anh hùng lịch sử nhưng không rèn luyện bản thân', C: 'Cho rằng việc xây dựng đất nước là của riêng người lớn', D: 'Tự ý làm theo cảm tính, không cần kỉ luật' }, correct_answer: 'A' })
];
