module.exports = [
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Làm sạch nước",source_unit:"Chất",source_lesson:"Bài 3. Sự ô nhiễm và bảo vệ nguồn nước",skill_tag:["science-life","reasoning"],difficulty:"vận dụng",type:"single_choice",question:"Vì sao nước nhìn trong vẫn có thể không an toàn để uống trực tiếp?",options:{A:"Vì có thể còn vi khuẩn hoặc chất bẩn hoà tan không nhìn thấy",B:"Vì nước trong thì chắc chắn có đường",C:"Vì mọi nước trong đều là nước mưa",D:"Vì nước chỉ an toàn khi có màu xanh"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Phòng chống bão",source_unit:"Chất",source_lesson:"Bài 6. Gió, bão và phòng chống bão",skill_tag:["safety","application"],difficulty:"vận dụng",type:"single_choice",question:"Khi nghe tin sắp có bão mạnh, việc chuẩn bị nào phù hợp nhất?",options:{A:"Chằng chống cửa, cất vật dễ bay và theo dõi hướng dẫn của người lớn",B:"Ra ngoài trời xem gió mạnh đến đâu",C:"Tắm mưa cho vui",D:"Mở hết cửa sổ để gió lùa vào"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Ánh sáng và bóng tối",source_unit:"Năng lượng",source_lesson:"Bài 8, 9",skill_tag:["experiment","light"],difficulty:"thông hiểu",type:"single_choice",question:"Khi đặt một quyển sách chắn giữa đèn pin và tường, vùng tối xuất hiện trên tường vì: ",options:{A:"Ánh sáng truyền qua mọi vật như nhau",B:"Quyển sách cản đường truyền của ánh sáng",C:"Tường tự tạo bóng tối",D:"Đèn pin hết pin ngay lập tức"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Dinh dưỡng và sức khoẻ",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 23 đến 26",skill_tag:["health","scenario"],difficulty:"vận dụng",type:"single_choice",question:"Bạn Nam thường bỏ bữa sáng nhưng lại ăn nhiều quà vặt trước giờ học. Thói quen này dễ gây hậu quả nào?",options:{A:"Cơ thể dễ mệt mỏi, khó tập trung học tập",B:"Luôn khoẻ hơn vì ăn linh tinh",C:"Không ảnh hưởng gì đến sức khoẻ",D:"Chỉ làm thay đổi màu áo"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Phòng tránh đuối nước",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 27. Phòng tránh đuối nước",skill_tag:["safety","reasoning"],difficulty:"thông hiểu",type:"single_choice",question:"Vì sao học sinh không nên tự ý cứu bạn bị đuối nước khi mình chưa biết bơi?",options:{A:"Vì có thể làm cả hai cùng gặp nguy hiểm",B:"Vì nước rất lạnh",C:"Vì như vậy sẽ làm nước bẩn",D:"Vì người bị nạn luôn tự bơi được vào bờ"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Thực vật và điều kiện sống",source_unit:"Thực vật và động vật",source_lesson:"Bài 15",skill_tag:["biology","inference"],difficulty:"vận dụng",type:"single_choice",question:"Hai cây cùng loại được trồng như nhau, chỉ khác là một cây để nơi đủ sáng, một cây đặt lâu ngày trong góc tối. Cây ở góc tối thường yếu hơn vì: ",options:{A:"Thiếu ánh sáng cần cho sự sống và phát triển",B:"Ánh sáng làm cây nặng hơn",C:"Góc tối có nhiều không khí hơn",D:"Cây không cần ánh sáng nếu đã tưới nước"},correct_answer:"A"},

  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Đất và bảo vệ đất",source_unit:"Chất",source_lesson:"Bài 1, 2",skill_tag:["environment","application"],difficulty:"vận dụng",type:"single_choice",question:"Biện pháp nào góp phần bảo vệ đất trồng ở vùng đồi dốc?",options:{A:"Trồng cây phủ xanh và hạn chế chặt phá rừng",B:"Đốt sạch cây cỏ trên đồi mỗi tháng",C:"Để đất trống sau mưa lớn",D:"Đổ nhiều rác nhựa lên mặt đất"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Dung dịch và tách chất",source_unit:"Chất",source_lesson:"Bài 3. Hỗn hợp và dung dịch",skill_tag:["science-process","application"],difficulty:"vận dụng",type:"single_choice",question:"Muốn thu lại muối từ cốc nước muối, cách làm phù hợp nhất là: ",options:{A:"Lọc qua rây lớn",B:"Để nước bay hơi dần",C:"Cho thêm cát vào cốc",D:"Đặt nam châm cạnh cốc"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Điện và an toàn điện",source_unit:"Năng lượng",source_lesson:"Bài 9. Mạch điện đơn giản. Vật dẫn điện và vật cách điện",skill_tag:["safety","electricity"],difficulty:"vận dụng",type:"single_choice",question:"Khi thấy dây điện bị hở ngoài sân sau mưa, em nên làm gì?",options:{A:"Lấy que kim loại gạt sang một bên",B:"Báo ngay cho người lớn và tránh xa khu vực đó",C:"Chạm thử xem còn điện không",D:"Đứng lên vũng nước để quan sát gần hơn"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Sinh sản của thực vật",source_unit:"Thực vật và động vật",source_lesson:"Bài 13, 14",skill_tag:["biology","comparison"],difficulty:"thông hiểu",type:"single_choice",question:"Điểm khác nhau cơ bản giữa sinh sản bằng hạt và sinh sản sinh dưỡng ở thực vật là gì?",options:{A:"Sinh sản bằng hạt cần có hoa, quả, hạt; sinh dưỡng tạo cây mới từ một bộ phận của cây",B:"Hai cách hoàn toàn giống nhau",C:"Sinh dưỡng chỉ xảy ra ở động vật",D:"Sinh sản bằng hạt không liên quan gì đến cây mẹ"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Vi khuẩn và phòng bệnh",source_unit:"Vi khuẩn",source_lesson:"Bài 20",skill_tag:["health","prevention"],difficulty:"vận dụng",type:"single_choice",question:"Thói quen nào giúp hạn chế bệnh do vi khuẩn gây ra nhiều nhất trong sinh hoạt hằng ngày?",options:{A:"Rửa tay sạch trước khi ăn và sau khi đi vệ sinh",B:"Ăn thức ăn ôi thiu để tiết kiệm",C:"Dùng chung cốc nước với người đang ốm",D:"Bỏ qua việc che đậy thức ăn"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Bảo vệ môi trường",source_unit:"Sinh vật và môi trường",source_lesson:"Bài 28, 29",skill_tag:["environment","systems"],difficulty:"vận dụng",type:"single_choice",question:"Một nhà máy xả nước thải chưa xử lí xuống sông. Ảnh hưởng nào dễ xuất hiện trước hết?",options:{A:"Nguồn nước bị ô nhiễm, sinh vật dưới nước bị tác động",B:"Nước sông tự trong hơn",C:"Cây trên bờ lớn nhanh ngay",D:"Không có thay đổi nào"},correct_answer:"A"},

  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Viết báo cáo thảo luận nhóm",source_unit:"Mỗi người một vẻ",source_lesson:"Bài 6 đến 8",skill_tag:["functional-writing","organization"],difficulty:"vận dụng",type:"single_choice",question:"Muốn báo cáo thảo luận nhóm rõ ràng, mục nào nên được trình bày nổi bật?",options:{A:"Nhiệm vụ, ý kiến chính và kết quả thống nhất của nhóm",B:"Chỉ cảm xúc riêng của người viết",C:"Tên quán ăn yêu thích của từng bạn",D:"Càng nhiều câu đùa càng tốt"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Bài văn kể lại một sự việc",source_unit:"Trải nghiệm và khám phá",source_lesson:"Bài 9 đến 11",skill_tag:["writing","sequence"],difficulty:"vận dụng",type:"single_choice",question:"Khi thuật lại một sự việc đáng nhớ, cách sắp xếp nào giúp người đọc dễ theo dõi nhất?",options:{A:"Theo trình tự diễn biến từ đầu đến cuối",B:"Nêu ngẫu nhiên các chi tiết nhớ được",C:"Chỉ kể phần kết thúc",D:"Lặp lại một ý nhiều lần"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Tính từ",source_unit:"Niềm vui sáng tạo",source_lesson:"Bài 21 đến 25",skill_tag:["grammar","effect"],difficulty:"thông hiểu",type:"single_choice",question:"Tính từ trong câu 'Mặt hồ buổi sớm phẳng lặng và trong veo.' giúp làm nổi bật điều gì?",options:{A:"Đặc điểm của mặt hồ",B:"Tên của hồ",C:"Thời gian một cách trực tiếp",D:"Người kể chuyện"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Dấu gạch ngang",source_unit:"Chắp cánh ước mơ",source_lesson:"Bài 27, 29",skill_tag:["punctuation","usage"],difficulty:"vận dụng",type:"single_choice",question:"Trong câu 'Lan reo lên: - Ôi, cuối cùng chúng mình cũng hoàn thành rồi!', dấu gạch ngang có tác dụng gì?",options:{A:"Đánh dấu lời nói trực tiếp",B:"Ngăn cách trạng ngữ",C:"Nối hai tiếng trong từ ghép",D:"Kết thúc câu hỏi"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Thư từ",source_unit:"Chắp cánh ước mơ",source_lesson:"Bài 31, 32",skill_tag:["functional-writing","purpose"],difficulty:"vận dụng",type:"single_choice",question:"Nếu viết thư hỏi thăm bạn cũ, nội dung nào là phù hợp nhất?",options:{A:"Lời chào, lí do viết thư, hỏi thăm tình hình và lời chúc",B:"Chỉ ghi đúng một dòng tên người gửi",C:"Liệt kê toàn bộ bài tập Toán",D:"Viết không cần mở đầu và kết thúc"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đọc hiểu và cảm xúc",source_unit:"Sống để yêu thương",source_lesson:"Nhiều bài đọc",skill_tag:["reading","inference"],difficulty:"vận dụng",type:"single_choice",passage:"Bà ngoại ngồi vá lại chiếc áo cũ cho em. Đôi tay bà chậm nhưng rất khéo. Em ngồi bên cạnh, nghe mùi trầu thơm thoảng và thấy lòng mình ấm lạ.",question:"Chi tiết nào góp phần thể hiện tình cảm yêu thương, gần gũi rõ nhất?",options:{A:"Đôi tay bà chậm nhưng rất khéo và cảm giác ấm áp của bạn nhỏ",B:"Chiếc áo có màu gì",C:"Nhà bạn nhỏ rộng hay hẹp",D:"Bà ngồi ở chiếc ghế nào"},correct_answer:"A"},

  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Bài văn tả phong cảnh",source_unit:"Thiên nhiên kì thú",source_lesson:"Bài 9 đến 16",skill_tag:["writing","description"],difficulty:"vận dụng",type:"single_choice",question:"Khi tả một cảnh đẹp buổi sớm, chi tiết nào giúp đoạn văn giàu hình ảnh hơn cả?",options:{A:"Màu trời, ánh nắng, âm thanh và cảm giác của người quan sát",B:"Chỉ nêu đúng tên địa điểm",C:"Liệt kê thật nhiều số liệu không liên quan",D:"Chỉ nói mình thích hay không thích"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Bài văn tả người",source_unit:"Vẻ đẹp cuộc sống; Thế giới của chúng ta",source_lesson:"Bài 1 đến 8; Bài 25, 26",skill_tag:["writing","portrait"],difficulty:"vận dụng",type:"single_choice",question:"Muốn bài văn tả người chân thực và sinh động, em nên chú ý điều gì nhất?",options:{A:"Kết hợp ngoại hình, hoạt động và nét tính cách tiêu biểu",B:"Chỉ kể chiều cao cân nặng",C:"Chép một đoạn văn mẫu không sửa",D:"Không cần nêu cảm nghĩ"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Cách nối các vế câu ghép",source_unit:"Vẻ đẹp cuộc sống",source_lesson:"Bài 3, 5",skill_tag:["grammar","logic"],difficulty:"vận dụng",type:"single_choice",question:"Cặp quan hệ từ nào thích hợp nhất để nối hai vế câu chỉ điều kiện - kết quả?",options:{A:"nếu ... thì ...",B:"tuy ... nhưng ...",C:"vì ... nên ...",D:"không những ... mà còn ..."},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn thể hiện tình cảm, cảm xúc",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 23, 24",skill_tag:["emotion","writing"],difficulty:"vận dụng",type:"single_choice",question:"Để đoạn văn bày tỏ cảm xúc về một chuyến đi thuyết phục hơn, em nên: ",options:{A:"Chọn chi tiết đáng nhớ và diễn tả cảm xúc gắn với chi tiết đó",B:"Chỉ liệt kê tên các địa điểm đã đi qua",C:"Viết thật chung chung để khỏi sai",D:"Không cần nêu cảm xúc thật của mình"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn nêu ý kiến phản đối",source_unit:"Thế giới của chúng ta",source_lesson:"Bài 27 đến 30",skill_tag:["critical-thinking","argument"],difficulty:"vận dụng",type:"single_choice",question:"Khi phản đối việc sử dụng điện thoại quá nhiều, câu mở đầu nào phù hợp nhất?",options:{A:"Em không đồng tình với việc học sinh dành quá nhiều thời gian cho điện thoại vì điều đó ảnh hưởng đến học tập và sức khoẻ.",B:"Điện thoại có nhiều màu sắc khác nhau.",C:"Mỗi ngày đều có 24 giờ.",D:"Em rất thích xem hoạt hình."},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Liên kết đoạn và ý chính",source_unit:"Hương sắc trăm miền; Tiếp bước cha ông",source_lesson:"Nhiều bài",skill_tag:["reading","cohesion"],difficulty:"vận dụng",type:"single_choice",passage:"Trưa hè, con đường làng vắng lặng. Chỉ có tiếng võng đưa kẽo kẹt và mùi rơm mới thoảng trong gió. Xa xa, đàn trâu thong thả trở về từ bãi cỏ.",question:"Từ ngữ nào góp phần gợi rõ nhất vẻ yên ả của khung cảnh?",options:{A:"vắng lặng, thong thả",B:"con đường",C:"đàn trâu",D:"trưa hè"},correct_answer:"A"}
];

