module.exports = [
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Xưng hô trong họ hàng",source_unit:"Gia đình",source_lesson:"Bài 1. Họ hàng và những ngày kỉ niệm của gia đình",skill_tag:["family","application"],difficulty:"vận dụng",type:"single_choice",question:"Mẹ đưa Mai đến thăm em gái của bà ngoại. Mai nên xưng hô phù hợp nhất với người đó là:",options:{A:"Bà",B:"Dì hoặc bà con bên ngoại tuỳ cách xưng hô gia đình",C:"Cô giáo",D:"Bạn"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Hoả hoạn khi ở nhà",source_unit:"Gia đình",source_lesson:"Bài 2. Phòng tránh hoả hoạn khi ở nhà",skill_tag:["safety","reasoning"],difficulty:"thông hiểu",type:"single_choice",question:"Vì sao không nên trốn trong phòng kín khi xảy ra cháy trong nhà?",options:{A:"Vì sẽ khó nghe điện thoại",B:"Vì khói có thể gây ngạt và cản trở việc thoát ra ngoài",C:"Vì phòng kín luôn rất lạnh",D:"Vì lửa không thể vào phòng kín"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Hoạt động kết nối với cộng đồng",source_unit:"Trường học",source_lesson:"Bài 5. Hoạt động kết nối với cộng đồng",skill_tag:["community","application"],difficulty:"vận dụng",type:"single_choice",question:"Lớp em muốn thực hiện một hoạt động kết nối với cộng đồng ngay trong khả năng học sinh tiểu học. Phương án nào phù hợp nhất?",options:{A:"Thu gom giấy vụn gây quỹ tặng sách cho thư viện lớp dưới",B:"Tự ý đi vận động tiền ở nơi xa không có người lớn",C:"Nghỉ học để đi làm thuê gây quỹ",D:"Chỉ treo khẩu hiệu mà không tham gia việc gì"},correct_answer:"A"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Sản xuất thủ công và công nghiệp",source_unit:"Cộng đồng địa phương",source_lesson:"Bài 10. Hoạt động sản xuất thủ công và công nghiệp",skill_tag:["classification","production"],difficulty:"vận dụng",type:"single_choice",question:"Hoạt động nào thuộc sản xuất thủ công nhiều hơn sản xuất công nghiệp?",options:{A:"Làm gốm bằng tay ở làng nghề",B:"Lắp ráp ô tô trong nhà máy lớn",C:"Sản xuất xi măng bằng dây chuyền tự động",D:"Chế tạo linh kiện điện tử hàng loạt"},correct_answer:"A"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Bộ phận của động vật",source_unit:"Thực vật và động vật",source_lesson:"Bài 15. Một số bộ phận của động vật và chức năng của chúng",skill_tag:["biology","matching"],difficulty:"vận dụng",type:"matching",question:"Ghép bộ phận của động vật với chức năng phù hợp.",items:[{label:"Cánh chim",correct_match:"Giúp bay"},{label:"Vây cá",correct_match:"Giúp bơi"},{label:"Chân mèo",correct_match:"Giúp di chuyển trên cạn"}],option_pool:["Giúp bay","Giúp bơi","Giúp di chuyển trên cạn"]},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Mặt Trời, Trái Đất, Mặt Trăng",source_unit:"Trái Đất và bầu trời",source_lesson:"Bài 29. Mặt Trời, Trái Đất, Mặt Trăng",skill_tag:["astronomy","inference"],difficulty:"thông hiểu",type:"single_choice",question:"Vì sao ban ngày thường sáng hơn ban đêm?",options:{A:"Vì ban ngày Trái Đất nhận được ánh sáng từ Mặt Trời",B:"Vì Mặt Trăng to hơn Mặt Trời",C:"Vì ban đêm không có không khí",D:"Vì các ngôi sao tắt hết vào ban đêm"},correct_answer:"A"},

  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Chọn phương tiện học tập",source_unit:"Mở đầu",source_lesson:"Bài 1. Làm quen với phương tiện học tập môn Lịch sử và Địa lí",skill_tag:["map-reading","tool-choice"],difficulty:"vận dụng",type:"single_choice",question:"Muốn biết thứ tự trước sau của ba sự kiện lịch sử, em nên ưu tiên sử dụng phương tiện nào?",options:{A:"Trục thời gian",B:"Bản đồ địa hình",C:"Bảng nhân chia",D:"Kính lúp"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Lịch sử và văn hoá địa phương",source_unit:"Địa phương em",source_lesson:"Bài 3. Lịch sử và văn hoá truyền thống địa phương em",skill_tag:["heritage","application"],difficulty:"vận dụng",type:"single_choice",question:"Để giới thiệu đúng về một di tích ở địa phương, nguồn thông tin nào đáng tin cậy hơn cả?",options:{A:"Bảng giới thiệu tại di tích và tư liệu chính thống của địa phương",B:"Tin đồn trên mạng không rõ nguồn",C:"Lời kể thêm bớt cho hấp dẫn",D:"Ý kiến của người chưa từng đến đó"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Văn minh sông Hồng",source_unit:"Đồng bằng Bắc Bộ",source_lesson:"Bài 11. Sông Hồng và văn minh sông Hồng",skill_tag:["cause-effect","history-geography"],difficulty:"thông hiểu",type:"single_choice",question:"Sông Hồng có vai trò lớn đối với sự hình thành văn minh sông Hồng chủ yếu vì:",options:{A:"Bồi đắp phù sa, cung cấp nước và tạo điều kiện cho cư dân sinh sống, sản xuất",B:"Làm xuất hiện núi lửa",C:"Tạo khí hậu băng giá",D:"Ngăn hoàn toàn mọi hoạt động giao thông"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Thăng Long - Hà Nội",source_unit:"Đồng bằng Bắc Bộ",source_lesson:"Bài 12. Thăng Long - Hà Nội",skill_tag:["comparison","urban-history"],difficulty:"vận dụng",type:"single_choice",question:"Điểm nào cho thấy Hà Nội vừa mang giá trị lịch sử lâu đời vừa là trung tâm phát triển hiện nay?",options:{A:"Có nhiều di tích lịch sử và đồng thời là Thủ đô của cả nước",B:"Chỉ nổi tiếng vì có nhiều núi cao",C:"Là nơi duy nhất có trường học",D:"Không có hoạt động văn hoá nào"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Tây Nguyên và Nam Bộ",source_unit:"Tây Nguyên; Nam Bộ",source_lesson:"Bài 21, 25",skill_tag:["comparison","region"],difficulty:"vận dụng",type:"single_choice",question:"Nhận xét nào đúng khi so sánh hoạt động sản xuất tiêu biểu của Tây Nguyên và Nam Bộ?",options:{A:"Tây Nguyên nổi bật cây công nghiệp lâu năm, Nam Bộ nổi bật lúa gạo và cây ăn quả ở nhiều nơi",B:"Cả hai vùng chỉ làm nghề biển",C:"Cả hai vùng đều chỉ có ruộng bậc thang",D:"Nam Bộ không có sông ngòi"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Bảo tồn di sản",source_unit:"Nhiều chủ đề",source_lesson:"Các bài về di tích, di sản",skill_tag:["citizenship","heritage"],difficulty:"vận dụng",type:"single_choice",question:"Khi tham quan di sản văn hoá, hành vi nào thể hiện ý thức bảo tồn tốt nhất?",options:{A:"Khắc tên lên tường để ghi dấu kỉ niệm",B:"Giữ vệ sinh, nghe hướng dẫn và không chạm vào hiện vật khi bị cấm",C:"Tự ý lấy một mảnh gạch cổ đem về",D:"Leo trèo lên khu vực bảo vệ để chụp ảnh"},correct_answer:"B"},

  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Đơn vị hành chính và bản đồ",source_unit:"Đất nước và con người Việt Nam",source_lesson:"Bài 1, 2",skill_tag:["map-thinking","application"],difficulty:"vận dụng",type:"single_choice",question:"Muốn biết một tỉnh thuộc vùng nào và giáp những địa phương nào, em nên xem trực tiếp trên: ",options:{A:"Bản đồ hành chính Việt Nam",B:"Trục thời gian lịch sử",C:"Một bài thơ",D:"Nhãn vở học sinh"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Biển Đông",source_unit:"Đất nước và con người Việt Nam",source_lesson:"Bài 3. Biển, đảo Việt Nam",skill_tag:["marine","reasoning"],difficulty:"vận dụng",type:"single_choice",question:"Vì sao bảo vệ biển, đảo có ý nghĩa không chỉ về kinh tế mà còn về chủ quyền quốc gia?",options:{A:"Vì biển, đảo gắn với lãnh thổ và an ninh của đất nước",B:"Vì biển chỉ để ngắm cảnh",C:"Vì mọi nước đều có quyền như nhau trên biển Việt Nam",D:"Vì bảo vệ biển không liên quan đến người dân"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Nhà nước Phù Nam và Chăm-pa",source_unit:"Những quốc gia đầu tiên trên lãnh thổ Việt Nam",source_lesson:"Bài 6, 7",skill_tag:["comparison","history"],difficulty:"thông hiểu",type:"single_choice",question:"Việc học về Phù Nam và Chăm-pa giúp em hiểu thêm điều gì?",options:{A:"Trên lãnh thổ nước ta từng tồn tại nhiều quốc gia cổ với dấu ấn lịch sử, văn hoá riêng",B:"Nước ta chỉ có một nền văn hoá duy nhất từ đầu",C:"Lịch sử chỉ gắn với vùng núi",D:"Các quốc gia cổ không liên quan đến hiện nay"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Điện Biên Phủ và Chiến dịch Hồ Chí Minh",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 15, 16",skill_tag:["comparison","modern-history"],difficulty:"vận dụng",type:"single_choice",question:"Điểm giống nhau nổi bật giữa Chiến thắng Điện Biên Phủ 1954 và Chiến dịch Hồ Chí Minh 1975 là gì?",options:{A:"Đều là những thắng lợi lớn góp phần quyết định trong sự nghiệp giải phóng dân tộc",B:"Đều diễn ra ở cùng một địa điểm",C:"Đều chống quân Mông - Nguyên",D:"Đều xảy ra trước năm 1900"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Láng giềng và hợp tác",source_unit:"Các nước láng giềng",source_lesson:"Bài 18 đến Bài 21",skill_tag:["regional-cooperation","application"],difficulty:"vận dụng",type:"single_choice",question:"Khi tìm hiểu các nước láng giềng, điều nào giúp quan hệ giữa các quốc gia ngày càng tốt đẹp hơn?",options:{A:"Tôn trọng chủ quyền, hợp tác và hiểu biết lẫn nhau",B:"So sánh để chê bai văn hoá nước khác",C:"Tự ý sử dụng tài nguyên của nước khác",D:"Không cần học về các nước xung quanh"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Thế giới xanh - sạch - đẹp",source_unit:"Chung tay xây dựng thế giới",source_lesson:"Bài 26, 27",skill_tag:["global-citizenship","behavior"],difficulty:"vận dụng",type:"single_choice",question:"Việc phân loại rác, tiết kiệm nước và hạn chế đồ nhựa dùng một lần thể hiện điều gì?",options:{A:"Chung tay bảo vệ môi trường và góp phần xây dựng thế giới xanh - sạch - đẹp",B:"Chỉ là việc của người lớn",C:"Không liên quan đến học sinh",D:"Làm cuộc sống bất tiện nên không cần"},correct_answer:"A"}
];
