module.exports = [
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Nước và đời sống",source_unit:"Chất",source_lesson:"Bài 1. Tính chất của nước và nước với cuộc sống",skill_tag:["application","science-life"],difficulty:"thông hiểu",type:"single_choice",question:"Ở sân trường có hai chậu: một chậu đựng nước trong chai, một chậu đựng nước trong bát rộng. Sau một ngày nắng, chậu nào dễ thấy lượng nước giảm nhanh hơn?",options:{A:"Chậu nước trong bát rộng vì nước dễ bay hơi hơn",B:"Chậu nước trong chai vì có nắp",C:"Hai chậu luôn giảm như nhau",D:"Không chậu nào giảm"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Sự chuyển thể của nước",source_unit:"Chất",source_lesson:"Bài 2. Sự chuyển thể của nước",skill_tag:["inference","water-cycle"],difficulty:"thông hiểu",type:"single_choice",question:"Buổi trưa nắng, vũng nước trước cổng trường cạn dần. Hiện tượng này thuộc quá trình nào?",options:{A:"Nóng chảy",B:"Bay hơi",C:"Đông đặc",D:"Ngưng tụ"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Bảo vệ nguồn nước",source_unit:"Chất",source_lesson:"Bài 3. Sự ô nhiễm và bảo vệ nguồn nước",skill_tag:["scenario","environment"],difficulty:"vận dụng",type:"single_choice",question:"Khu dân cư gần nhà em có mương thoát nước sinh hoạt chảy ra ao. Việc làm nào giúp bảo vệ nguồn nước hiệu quả nhất?",options:{A:"Đổ thêm rác xuống ao để lấp mùi",B:"Thu gom rác đúng nơi quy định và không xả nước bẩn chưa xử lí xuống ao",C:"Chỉ chờ trời mưa lớn cuốn trôi",D:"Che tạm mặt ao bằng bạt"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Không khí và cháy",source_unit:"Chất",source_lesson:"Bài 4. Không khí có ở đâu? Tính chất và thành phần của không khí",skill_tag:["reasoning","air"],difficulty:"thông hiểu",type:"single_choice",question:"Vì sao khi úp cốc thuỷ tinh kín lên một ngọn nến đang cháy, ngọn nến sẽ tắt sau một lúc?",options:{A:"Vì cốc làm nến lạnh đi ngay lập tức",B:"Vì lượng không khí cần cho sự cháy trong cốc dần hết",C:"Vì ánh sáng không lọt vào cốc",D:"Vì ngọn nến sợ bóng tối"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Ánh sáng",source_unit:"Năng lượng",source_lesson:"Bài 8. Ánh sáng và sự truyền ánh sáng",skill_tag:["application","light"],difficulty:"vận dụng",type:"single_choice",question:"Lan muốn đọc sách ở góc bàn học buổi tối mà không bị bóng tay che chữ. Cách đặt đèn bàn hợp lí nhất là:",options:{A:"Đặt đèn phía sau lưng để bóng rọi lên trang sách",B:"Đặt đèn phía đối diện người viết và đủ gần để chiếu sáng mặt bàn",C:"Tắt hết đèn để tập quen bóng tối",D:"Đặt đèn dưới gầm bàn"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Âm thanh",source_unit:"Năng lượng",source_lesson:"Bài 10. Âm thanh và sự truyền âm thanh; Bài 11. Âm thanh trong cuộc sống",skill_tag:["scenario","sound"],difficulty:"thông hiểu",type:"single_choice",question:"Trong thư viện, việc nói nhỏ giúp bảo vệ môi trường học tập vì:",options:{A:"Âm thanh nhỏ truyền đi nhanh hơn",B:"Âm thanh quá lớn có thể gây ồn, ảnh hưởng người khác",C:"Âm thanh nhỏ làm sách dày hơn",D:"Nói nhỏ giúp đèn sáng hơn"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Truyền nhiệt",source_unit:"Năng lượng",source_lesson:"Bài 12. Nhiệt độ và sự truyền nhiệt; Bài 13. Vật dẫn nhiệt tốt, vật dẫn nhiệt kém",skill_tag:["application","heat"],difficulty:"vận dụng",type:"single_choice",question:"Khi bê nồi canh nóng, người ta thường dùng khăn vải dày hoặc quai nhựa vì:",options:{A:"Vải và nhựa dẫn nhiệt kém hơn kim loại",B:"Vải và nhựa làm canh nguội ngay",C:"Kim loại quá nhẹ nên khó cầm",D:"Khăn vải có thể thay nắp nồi"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Thực vật cần gì để sống",source_unit:"Thực vật và động vật",source_lesson:"Bài 15. Thực vật cần gì để sống?",skill_tag:["experiment","plants"],difficulty:"thông hiểu",type:"single_choice",question:"Một nhóm học sinh trồng ba chậu đậu giống nhau: chậu A đủ nước và ánh sáng, chậu B không được tưới nước, chậu C để trong hộp kín thiếu ánh sáng. Chậu nào nhiều khả năng phát triển tốt nhất?",options:{A:"Chậu A",B:"Chậu B",C:"Chậu C",D:"Cả ba như nhau"},correct_answer:"A"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Động vật cần gì để sống",source_unit:"Thực vật và động vật",source_lesson:"Bài 16. Động vật cần gì để sống?",skill_tag:["reasoning","animals"],difficulty:"thông hiểu",type:"single_choice",question:"Nếu nuôi thỏ trong chuồng kín, không cho uống nước và ít không khí, điều gì dễ xảy ra nhất?",options:{A:"Thỏ lớn rất nhanh",B:"Thỏ khó sống khoẻ mạnh vì thiếu nhu cầu thiết yếu",C:"Thỏ sẽ tự tạo ra nước",D:"Không ảnh hưởng gì"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Nấm",source_unit:"Nấm",source_lesson:"Bài 20. Nấm ăn và nấm trong chế biến thực phẩm; Bài 21. Nấm gây hỏng thực phẩm và nấm độc",skill_tag:["classification","safety"],difficulty:"vận dụng",type:"single_choice",question:"Phát biểu nào cho thấy em hiểu đúng về nấm trong đời sống?",options:{A:"Nấm nào mọc ngoài tự nhiên cũng ăn được",B:"Có nấm có ích trong chế biến thực phẩm nhưng cũng có nấm gây hỏng hoặc gây độc",C:"Nấm không liên quan gì đến thức ăn",D:"Chỉ cây mới làm thực phẩm hỏng"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Dinh dưỡng",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 23. Vai trò của chất dinh dưỡng; Bài 24. Chế độ ăn uống cân bằng",skill_tag:["health","balanced-meal"],difficulty:"vận dụng",type:"single_choice",question:"Bữa trưa nào cân đối hơn cho học sinh tiểu học?",options:{A:"Chỉ có xúc xích và nước ngọt",B:"Cơm, cá hoặc thịt, rau xanh, trái cây và nước",C:"Chỉ có bánh ngọt",D:"Chỉ có mì tôm khô"},correct_answer:"B"},
  {grade:4,book:"Khoa học 4 - Kết nối tri thức",subject:"Khoa học",topic:"Chuỗi thức ăn",source_unit:"Sinh vật và môi trường",source_lesson:"Bài 29. Chuỗi thức ăn trong tự nhiên",skill_tag:["reasoning","ecosystem"],difficulty:"vận dụng",type:"single_choice",question:"Trong chuỗi thức ăn cỏ → châu chấu → ếch → rắn, nếu số lượng châu chấu giảm mạnh thì điều gì dễ xảy ra tiếp theo?",options:{A:"Ếch có thể giảm vì thiếu thức ăn",B:"Cỏ mất hết ngay lập tức",C:"Rắn tăng rất nhanh vì vui hơn",D:"Không ảnh hưởng đến sinh vật nào"},correct_answer:"A"}
];
