module.exports = [
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Đất đối với cây trồng",source_unit:"Chất",source_lesson:"Bài 1. Thành phần và vai trò của đất đối với cây trồng",skill_tag:["inference","soil"],difficulty:"thông hiểu",type:"single_choice",question:"Một thửa ruộng được cải tạo bằng cách làm đất tơi xốp và bổ sung mùn. Việc làm đó có ích nhất vì:",options:{A:"Giúp rễ dễ phát triển và nhận nước, chất dinh dưỡng tốt hơn",B:"Làm cây khỏi cần ánh sáng",C:"Thay thế hoàn toàn vai trò của nước",D:"Làm đất biến thành đá"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Hỗn hợp và dung dịch",source_unit:"Chất",source_lesson:"Bài 3. Hỗn hợp và dung dịch",skill_tag:["classification","matter"],difficulty:"vận dụng",type:"single_choice",question:"Trường hợp nào sau đây tạo thành dung dịch?",options:{A:"Cát trộn với sỏi",B:"Muối khuấy tan hoàn toàn trong nước",C:"Dầu ăn đổ vào nước rồi để yên",D:"Gạo trộn với đỗ xanh"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Sự biến đổi trạng thái",source_unit:"Chất",source_lesson:"Bài 4. Đặc điểm của chất ở trạng thái rắn, lỏng, khí; Bài 5. Sự biến đổi hoá học của chất",skill_tag:["comparison","matter"],difficulty:"vận dụng",type:"single_choice",question:"Hiện tượng nào chỉ là biến đổi trạng thái, không tạo ra chất mới?",options:{A:"Đường cháy thành màu nâu sẫm",B:"Sắt bị gỉ",C:"Nước đá tan thành nước",D:"Giấy đốt thành tro"},correct_answer:"C"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Biến đổi hoá học",source_unit:"Chất",source_lesson:"Bài 5. Sự biến đổi hoá học của chất",skill_tag:["reasoning","chemistry"],difficulty:"thông hiểu",type:"single_choice",question:"Dấu hiệu nào cho thấy một hiện tượng có thể là biến đổi hoá học?",options:{A:"Chỉ đổi hình dạng mà chất vẫn như cũ",B:"Xuất hiện chất mới như tro, gỉ hoặc mùi vị khác hẳn",C:"Đá lạnh tan thành nước",D:"Nước bay hơi"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Vai trò của năng lượng",source_unit:"Năng lượng",source_lesson:"Bài 7. Vai trò của năng lượng",skill_tag:["application","energy"],difficulty:"thông hiểu",type:"single_choice",question:"Một chiếc quạt điện hoạt động được là nhờ chủ yếu chuyển hoá năng lượng điện thành:",options:{A:"Năng lượng làm cánh quạt quay",B:"Năng lượng làm cây mọc",C:"Năng lượng làm nước đóng băng",D:"Năng lượng hoá học của thức ăn"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Mạch điện đơn giản",source_unit:"Năng lượng",source_lesson:"Bài 9. Mạch điện đơn giản. Vật dẫn điện và vật cách điện",skill_tag:["circuit","application"],difficulty:"vận dụng",type:"single_choice",question:"Trong mạch điện đơn giản dùng pin và bóng đèn, bộ phận nào dưới đây nếu bị đứt sẽ làm đèn không sáng?",options:{A:"Một đoạn dây dẫn nối mạch",B:"Vỏ nhựa bọc ngoài dây điện",C:"Bìa giấy kê dưới pin",D:"Mặt bàn đặt mạch"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Nguồn năng lượng tái tạo",source_unit:"Năng lượng",source_lesson:"Bài 11. Sử dụng năng lượng mặt trời, năng lượng gió, năng lượng nước chảy",skill_tag:["environment","energy"],difficulty:"vận dụng",type:"single_choice",question:"Nhà trường muốn chọn nguồn năng lượng vừa khai thác được nhiều lần, vừa giảm ô nhiễm. Lựa chọn nào phù hợp nhất?",options:{A:"Than đá",B:"Xăng dầu",C:"Năng lượng mặt trời",D:"Đốt rác nhựa"},correct_answer:"C"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Sinh sản của thực vật có hoa",source_unit:"Thực vật và động vật",source_lesson:"Bài 13. Sinh sản của thực vật có hoa",skill_tag:["biology","reasoning"],difficulty:"thông hiểu",type:"single_choice",question:"Bộ phận nào của hoa phát triển thành quả và hạt sau khi thụ phấn, thụ tinh?",options:{A:"Nhị và nhuỵ",B:"Cuống lá",C:"Rễ phụ",D:"Vỏ thân"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Vòng đời của động vật",source_unit:"Thực vật và động vật",source_lesson:"Bài 16. Vòng đời và sự phát triển của động vật",skill_tag:["life-cycle","biology"],difficulty:"vận dụng",type:"single_choice",question:"Nếu muốn nuôi tằm lấy kén, người nuôi phải hiểu vòng đời của tằm chủ yếu để làm gì?",options:{A:"Biết thời điểm chăm sóc phù hợp ở từng giai đoạn phát triển",B:"Làm cho tằm không cần ăn",C:"Biến tằm thành cây dâu",D:"Thay đổi màu sắc của kén"},correct_answer:"A"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Vi khuẩn có ích và có hại",source_unit:"Vi khuẩn",source_lesson:"Bài 19. Vi khuẩn có ích trong chế biến thực phẩm; Bài 20. Vi khuẩn gây bệnh ở người và cách phòng tránh",skill_tag:["classification","health"],difficulty:"vận dụng",type:"single_choice",question:"Nhận xét nào đúng về vi khuẩn?",options:{A:"Vi khuẩn luôn có hại",B:"Có vi khuẩn có ích trong chế biến thực phẩm, cũng có vi khuẩn gây bệnh",C:"Vi khuẩn chỉ sống trong nước biển",D:"Không thể phòng tránh bệnh do vi khuẩn"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Tuổi dậy thì và sức khoẻ",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 24. Nam và nữ; Bài 25. Chăm sóc sức khoẻ tuổi dậy thì",skill_tag:["health","respect"],difficulty:"thông hiểu",type:"single_choice",question:"Trong tuổi dậy thì, cách ứng xử nào phù hợp nhất?",options:{A:"Trêu chọc bạn vì sự thay đổi cơ thể",B:"Tôn trọng sự khác biệt, giữ vệ sinh cá nhân và chia sẻ với người tin cậy khi cần",C:"Bỏ qua mọi thay đổi vì không quan trọng",D:"Nghe theo mọi thông tin trên mạng không kiểm chứng"},correct_answer:"B"},
  {grade:5,book:"Khoa học 5 - Kết nối tri thức",subject:"Khoa học",topic:"Bảo vệ môi trường sống",source_unit:"Sinh vật và môi trường",source_lesson:"Bài 29. Tác động của con người và một số biện pháp bảo vệ môi trường",skill_tag:["environment","cause-effect"],difficulty:"vận dụng",type:"single_choice",question:"Một con suối đầu nguồn bị chặt phá rừng mạnh. Hậu quả nào dễ xảy ra hơn cả?",options:{A:"Đất giữ nước tốt hơn trước",B:"Dễ xói mòn, lũ quét và ảnh hưởng môi trường sống của sinh vật",C:"Nguồn nước tự sạch hơn",D:"Số lượng cây rừng tăng nhanh"},correct_answer:"B"}
];
