module.exports = [
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Vị trí địa lí Việt Nam",source_unit:"Đất nước và con người Việt Nam",source_lesson:"Bài 1. Vị trí địa lí, lãnh thổ, đơn vị hành chính, Quốc kì, Quốc huy, Quốc ca",skill_tag:["inference","national-territory"],difficulty:"thông hiểu",type:"single_choice",question:"Việt Nam vừa có biên giới đất liền, vừa tiếp giáp Biển Đông. Điều này tạo thuận lợi rõ nhất nào sau đây?",options:{A:"Mở rộng giao lưu với nhiều quốc gia bằng cả đường bộ và đường biển",B:"Làm cho mọi nơi trong nước có cùng khí hậu",C:"Khiến nước ta không cần bảo vệ chủ quyền biển đảo",D:"Chỉ phát triển được nghề nông"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Biển, đảo Việt Nam",source_unit:"Đất nước và con người Việt Nam",source_lesson:"Bài 3. Biển, đảo Việt Nam",skill_tag:["application","marine-economy"],difficulty:"vận dụng",type:"single_choice",question:"Một tỉnh ven biển muốn phát triển kinh tế nhưng đồng thời phải bảo vệ môi trường biển. Phương án nào phù hợp nhất?",options:{A:"Đổ rác thẳng xuống biển để tiết kiệm chi phí",B:"Khai thác hải sản hợp lí, kết hợp du lịch và bảo vệ hệ sinh thái biển",C:"Cấm hoàn toàn mọi hoạt động trên biển",D:"Chỉ phát triển nhà máy gần bờ không xử lí nước thải"},correct_answer:"B"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Văn Lang và Âu Lạc",source_unit:"Những quốc gia đầu tiên trên lãnh thổ Việt Nam",source_lesson:"Bài 5. Nhà nước Văn Lang, Nhà nước Âu Lạc",skill_tag:["comparison","history"],difficulty:"thông hiểu",type:"single_choice",question:"Điểm khác nổi bật gắn với nhà nước Âu Lạc so với Văn Lang là:",options:{A:"Có truyền thuyết về việc xây thành Cổ Loa gắn với An Dương Vương",B:"Là nhà nước duy nhất biết trồng lúa",C:"Không có vua đứng đầu",D:"Được thành lập sau Cách mạng tháng Tám"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Các triều đại phong kiến",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 8 đến Bài 13",skill_tag:["ordering","timeline"],difficulty:"vận dụng",type:"ordering",question:"Sắp xếp các sự kiện lịch sử sau theo thứ tự từ sớm đến muộn.",sentences:[{original_index:1,text:"Ngô Quyền chiến thắng Bạch Đằng năm 938."},{original_index:2,text:"Lý Công Uẩn dời đô ra Thăng Long."},{original_index:3,text:"Quân dân nhà Trần ba lần kháng chiến chống quân Mông - Nguyên."},{original_index:4,text:"Khởi nghĩa Lam Sơn thắng lợi."}],correct_answer:[1,2,3,4]},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Dời đô ra Thăng Long",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 9. Triều Lý và việc định đô ở Thăng Long",skill_tag:["reasoning","history"],difficulty:"vận dụng",type:"single_choice",question:"Việc Lý Công Uẩn quyết định dời đô ra Thăng Long cho thấy điều gì về tầm nhìn của người đứng đầu đất nước?",options:{A:"Biết lựa chọn nơi có vị trí thuận lợi cho sự phát triển lâu dài",B:"Muốn rời bỏ hoàn toàn đồng bằng",C:"Chỉ quan tâm đến việc xây nhiều cung điện",D:"Không coi trọng giao thông và dân cư"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Kháng chiến thời Trần",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 10. Triều Trần xây dựng đất nước và kháng chiến chống quân Mông - Nguyên xâm lược",skill_tag:["lesson-learned","history"],difficulty:"thông hiểu",type:"single_choice",question:"Bài học lớn rút ra từ các cuộc kháng chiến thời Trần là gì?",options:{A:"Chỉ cần thành luỹ kiên cố là đủ",B:"Sức mạnh đoàn kết toàn dân rất quan trọng trong bảo vệ đất nước",C:"Không cần chuẩn bị lương thực",D:"Muốn thắng phải rút khỏi đất nước"},correct_answer:"B"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Khởi nghĩa Lam Sơn và triều Hậu Lê",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 12. Khởi nghĩa Lam Sơn và Triều Hậu Lê",skill_tag:["meaning","history"],difficulty:"thông hiểu",type:"single_choice",question:"Ý nghĩa quan trọng của thắng lợi Lam Sơn là gì?",options:{A:"Chấm dứt ách đô hộ của quân Minh, khôi phục nền độc lập",B:"Mở đầu công cuộc Đổi mới",C:"Đưa nước ta gia nhập ASEAN",D:"Thiết lập nhà nước Văn Lang"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Các mốc 1945 - 1954 - 1975",source_unit:"Xây dựng và bảo vệ đất nước Việt Nam",source_lesson:"Bài 14, 15, 16",skill_tag:["matching","timeline"],difficulty:"vận dụng",type:"matching",question:"Ghép mốc năm với sự kiện lịch sử phù hợp.",items:[{label:"1945",correct_match:"Cách mạng tháng Tám thành công"},{label:"1954",correct_match:"Chiến thắng Điện Biên Phủ"},{label:"1975",correct_match:"Chiến dịch Hồ Chí Minh thắng lợi"}],option_pool:["Cách mạng tháng Tám thành công","Chiến thắng Điện Biên Phủ","Chiến dịch Hồ Chí Minh thắng lợi"]},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"ASEAN",source_unit:"Các nước láng giềng",source_lesson:"Bài 21. Hiệp hội các quốc gia Đông Nam Á",skill_tag:["international","purpose"],difficulty:"thông hiểu",type:"single_choice",question:"Việc các nước Đông Nam Á cùng tham gia ASEAN nhằm mục đích phù hợp nhất nào sau đây?",options:{A:"Hợp tác cùng phát triển và tăng cường quan hệ hữu nghị",B:"Xoá bỏ hoàn toàn bản sắc riêng của từng nước",C:"Chỉ để tổ chức thi đấu thể thao",D:"Thống nhất thành một quốc gia duy nhất"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Các châu lục và đại dương",source_unit:"Tìm hiểu thế giới",source_lesson:"Bài 22. Các châu lục và đại dương trên thế giới",skill_tag:["map-thinking","world"],difficulty:"vận dụng",type:"single_choice",question:"Một bạn nói: 'Châu lục của mình có diện tích rất lớn và trải dài từ vùng lạnh đến vùng nóng'. Bạn đó nhiều khả năng đang nói về châu lục nào?",options:{A:"Châu Á",B:"Châu Đại Dương",C:"Châu Nam Cực",D:"Châu Âu"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Văn minh cổ đại",source_unit:"Tìm hiểu thế giới",source_lesson:"Bài 24. Văn minh Ai Cập; Bài 25. Văn minh Hy Lạp",skill_tag:["inference","civilization"],difficulty:"thông hiểu",type:"single_choice",question:"Các nền văn minh cổ đại lớn thường hình thành trước hết ở nơi nào?",options:{A:"Ven các con sông lớn hoặc vùng thuận lợi cho sinh sống",B:"Trên những đỉnh núi băng giá",C:"Giữa hoang mạc không nguồn nước",D:"Chỉ ở các đảo nhỏ cô lập"},correct_answer:"A"},
  {grade:5,book:"Lịch sử và Địa lí 5 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Chung tay xây dựng thế giới",source_unit:"Chung tay xây dựng thế giới",source_lesson:"Bài 26. Xây dựng thế giới xanh - sạch - đẹp; Bài 27. Xây dựng thế giới hoà bình",skill_tag:["global-citizenship","application"],difficulty:"vận dụng",type:"single_choice",question:"Hành động nào của học sinh thể hiện đúng tinh thần 'chung tay xây dựng thế giới xanh - sạch - đẹp'?",options:{A:"Vứt pin cũ lẫn với rác sinh hoạt cho nhanh",B:"Tiết kiệm điện, trồng cây và nhắc mọi người giữ vệ sinh nơi công cộng",C:"Chỉ chờ người lớn giải quyết mọi việc môi trường",D:"Đốt lá nhựa để dọn sân"},correct_answer:"B"}
];
