module.exports = [
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Sử dụng bản đồ",source_unit:"Mở đầu",source_lesson:"Bài 1. Làm quen với phương tiện học tập môn Lịch sử và Địa lí",skill_tag:["map-reading","process"],difficulty:"thông hiểu",type:"single_choice",question:"Khi muốn biết một kí hiệu màu xanh trên bản đồ chỉ đối tượng nào, em nên thực hiện trước tiên bước nào?",options:{A:"Đo khoảng cách từ kí hiệu đến mép giấy",B:"Đọc bảng chú giải của bản đồ",C:"Tìm ngay tên tỉnh gần đó",D:"Nhìn màu bìa sách"},correct_answer:"B"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Địa phương em",source_unit:"Địa phương em",source_lesson:"Bài 2. Thiên nhiên và con người địa phương em",skill_tag:["inference","locality"],difficulty:"vận dụng",type:"single_choice",question:"Một địa phương có cửa biển, nhiều đầm phá và nghề nuôi trồng thuỷ sản phát triển. Nhận xét nào hợp lí nhất về mối quan hệ giữa thiên nhiên và hoạt động của con người ở đây?",options:{A:"Hoạt động sản xuất hầu như không phụ thuộc điều kiện tự nhiên",B:"Điều kiện sông, biển và mặt nước thuận lợi giúp người dân phát triển nghề thuỷ sản",C:"Người dân chỉ có thể làm nghề trồng lúa trên núi",D:"Địa phương đó chắc chắn không có giao thông đường thuỷ"},correct_answer:"B"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Trung du và miền núi Bắc Bộ",source_unit:"Trung du và miền núi Bắc Bộ",source_lesson:"Bài 5. Dân cư và hoạt động sản xuất ở vùng Trung du và miền núi Bắc Bộ",skill_tag:["region","application"],difficulty:"vận dụng",type:"single_choice",question:"Người dân ở một số nơi thuộc vùng Trung du và miền núi Bắc Bộ làm ruộng bậc thang chủ yếu để thích nghi với điều kiện nào?",options:{A:"Địa hình dốc, nhiều sườn núi",B:"Đất hoàn toàn bằng phẳng và ngập mặn",C:"Chỉ có cát ven biển",D:"Khí hậu quanh năm băng giá"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Đền Hùng",source_unit:"Trung du và miền núi Bắc Bộ",source_lesson:"Bài 7. Đền Hùng và lễ Giỗ Tổ Hùng Vương",skill_tag:["heritage","meaning"],difficulty:"thông hiểu",type:"single_choice",question:"Việc người dân cả nước hướng về lễ Giỗ Tổ Hùng Vương cho thấy điều gì nổi bật nhất?",options:{A:"Sự nhớ ơn cội nguồn dân tộc",B:"Mọi lễ hội đều chỉ để vui chơi",C:"Người Việt chỉ quan tâm đến vùng núi",D:"Đền Hùng là nơi buôn bán lớn"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Đồng bằng Bắc Bộ",source_unit:"Đồng bằng Bắc Bộ",source_lesson:"Bài 9. Dân cư và hoạt động sản xuất ở vùng Đồng bằng Bắc Bộ",skill_tag:["region","reasoning"],difficulty:"vận dụng",type:"single_choice",question:"Vì sao hệ thống đê điều ở vùng Đồng bằng Bắc Bộ có ý nghĩa rất quan trọng đối với sản xuất và đời sống?",options:{A:"Giúp ngăn lũ, bảo vệ làng mạc và đồng ruộng",B:"Dùng để nuôi cá biển xa bờ",C:"Tạo thêm nhiều núi cao",D:"Làm cho mùa đông nóng hơn"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Vùng Đồng bằng Bắc Bộ",source_unit:"Đồng bằng Bắc Bộ",source_lesson:"Bài 10. Một số nét văn hoá ở vùng Đồng bằng Bắc Bộ",skill_tag:["inference","culture"],difficulty:"thông hiểu",type:"single_choice",question:"Một bạn mô tả quê mình có làng nghề truyền thống, lễ hội mùa xuân và nhiều ngôi chùa cổ. Bạn ấy nhiều khả năng đang nói về vùng nào?",options:{A:"Đồng bằng Bắc Bộ",B:"Tây Nguyên",C:"Quần đảo Trường Sa",D:"Cao nguyên đá Đồng Văn"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Duyên hải miền Trung",source_unit:"Duyên hải miền Trung",source_lesson:"Bài 16. Dân cư và hoạt động sản xuất ở vùng Duyên hải miền Trung",skill_tag:["region","application"],difficulty:"vận dụng",type:"single_choice",question:"Ở nhiều tỉnh duyên hải miền Trung, nghề làm muối phát triển vì sao?",options:{A:"Có nhiều hồ băng quanh năm",B:"Ven biển, nắng nhiều và thuận lợi cho nước biển bốc hơi",C:"Đất đỏ ba dan rất dày",D:"Có nhiều rừng rậm, ít ánh nắng"},correct_answer:"B"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Cố đô Huế và phố cổ Hội An",source_unit:"Duyên hải miền Trung",source_lesson:"Bài 18. Cố đô Huế; Bài 19. Phố cổ Hội An",skill_tag:["comparison","heritage"],difficulty:"thông hiểu",type:"single_choice",question:"Điểm giống nhau nổi bật giữa Cố đô Huế và Phố cổ Hội An là gì?",options:{A:"Đều là di sản có giá trị lịch sử, văn hoá cần được bảo tồn",B:"Đều là cao nguyên trồng cà phê lớn",C:"Đều nằm sâu trong vùng núi cao",D:"Đều chỉ có ý nghĩa đối với riêng một tỉnh"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Tây Nguyên",source_unit:"Tây Nguyên",source_lesson:"Bài 21. Dân cư và hoạt động sản xuất ở vùng Tây Nguyên",skill_tag:["region","inference"],difficulty:"vận dụng",type:"single_choice",question:"Một khu vực có nhiều cao nguyên, đất đỏ ba dan và thích hợp trồng cà phê, cao su. Khu vực đó là:",options:{A:"Tây Nguyên",B:"Đồng bằng Bắc Bộ",C:"Vùng biển đảo",D:"Đồng bằng sông Hồng"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Lễ hội cồng chiêng",source_unit:"Tây Nguyên",source_lesson:"Bài 23. Lễ hội Cồng chiêng Tây Nguyên",skill_tag:["culture","meaning"],difficulty:"thông hiểu",type:"single_choice",question:"Lễ hội Cồng chiêng Tây Nguyên không chỉ là một hoạt động vui chơi mà còn góp phần:",options:{A:"Giữ gìn bản sắc văn hoá của cộng đồng",B:"Làm cho khí hậu mát hơn",C:"Thay thế hoàn toàn việc học ở trường",D:"Chứng minh mọi nơi đều có cùng phong tục"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Nam Bộ",source_unit:"Nam Bộ",source_lesson:"Bài 25. Dân cư và hoạt động sản xuất ở vùng Nam Bộ",skill_tag:["region","reasoning"],difficulty:"vận dụng",type:"single_choice",question:"Vì sao ở nhiều nơi thuộc Nam Bộ, ghe thuyền vẫn là phương tiện đi lại và vận chuyển quan trọng?",options:{A:"Do mạng lưới sông ngòi, kênh rạch dày đặc",B:"Vì khu vực này toàn núi cao hiểm trở",C:"Vì không có đồng bằng",D:"Vì đường bộ bị cấm hoàn toàn"},correct_answer:"A"},
  {grade:4,book:"Lịch sử và Địa lí 4 - Kết nối tri thức",subject:"Lịch sử và Địa lí",topic:"Thành phố Hồ Chí Minh và Địa đạo Củ Chi",source_unit:"Nam Bộ",source_lesson:"Bài 27. Thành phố Hồ Chí Minh; Bài 28. Địa đạo Củ Chi",skill_tag:["history","connection"],difficulty:"vận dụng",type:"single_choice",question:"Một bạn nói: 'Em muốn tham quan một địa điểm vừa giúp hiểu sự sáng tạo trong kháng chiến, vừa gắn với vùng đất Thành phố Hồ Chí Minh.' Bạn ấy nên đến đâu?",options:{A:"Văn Miếu - Quốc Tử Giám",B:"Địa đạo Củ Chi",C:"Cố đô Huế",D:"Hồ Gươm"},correct_answer:"B"}
];
