module.exports = [
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Họ hàng và xưng hô",source_unit:"Gia đình",source_lesson:"Bài 1. Họ hàng và những ngày kỉ niệm của gia đình",skill_tag:["scenario","family"],difficulty:"thông hiểu",type:"single_choice",question:"Trong buổi họp mặt gia đình, bạn Lan giới thiệu: 'Đây là ông bà nội, đây là dì ruột của mẹ em, còn đây là cô giáo chủ nhiệm đến chúc mừng.' Người nào không thuộc họ hàng của Lan?",options:{A:"Ông bà nội",B:"Dì ruột của mẹ",C:"Cô giáo chủ nhiệm",D:"Tất cả đều là họ hàng"},correct_answer:"C"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Ngày kỉ niệm gia đình",source_unit:"Gia đình",source_lesson:"Bài 1. Họ hàng và những ngày kỉ niệm của gia đình",skill_tag:["application","behavior"],difficulty:"vận dụng",type:"single_choice",question:"Gia đình Minh chuẩn bị mừng thọ ông. Việc làm nào của Minh thể hiện sự quan tâm đúng cách và hiểu ý nghĩa ngày kỉ niệm nhất?",options:{A:"Bật nhạc thật to để buổi vui hơn",B:"Hỏi ông về những kỉ niệm đáng nhớ rồi giúp bố mẹ chuẩn bị bàn ghế",C:"Tự ý lấy điện thoại của khách để chụp ảnh",D:"Rủ bạn sang chơi để đỡ buồn"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Phòng tránh hoả hoạn",source_unit:"Gia đình",source_lesson:"Bài 2. Phòng tránh hoả hoạn khi ở nhà",skill_tag:["ordering","safety"],difficulty:"vận dụng",type:"ordering",question:"Sắp xếp các việc nên làm khi phát hiện ổ cắm điện bốc khói ở nhà.",sentences:[{original_index:1,text:"Báo ngay cho người lớn và tránh xa khu vực nguy hiểm."},{original_index:2,text:"Ngắt nguồn điện nếu người lớn hướng dẫn và bảo đảm an toàn."},{original_index:3,text:"Tuyệt đối không chạm tay ướt vào ổ cắm."},{original_index:4,text:"Gọi cứu hoả nếu đám cháy lan rộng."}],correct_answer:[1,3,2,4]},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"An toàn ở trường",source_unit:"Trường học",source_lesson:"Bài 7. Giữ an toàn và vệ sinh ở trường",skill_tag:["scenario","school-safety"],difficulty:"vận dụng",type:"single_choice",question:"Cuối giờ ra chơi, sân trường còn ướt sau cơn mưa. Nhóm bạn định chạy đuổi bắt trên hành lang. Cách xử lí phù hợp nhất là gì?",options:{A:"Cùng chạy cho vui vì sắp vào lớp rồi",B:"Nhắc các bạn đi chậm, không xô đẩy và tránh khu vực trơn trượt",C:"Đứng nhìn vì đó là việc của cô trực",D:"Rủ thêm bạn khác tham gia để nhanh hết giờ"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Truyền thống trường em",source_unit:"Trường học",source_lesson:"Bài 6. Truyền thống trường em",skill_tag:["application","respect"],difficulty:"thông hiểu",type:"single_choice",question:"Lớp em muốn làm tờ giới thiệu về truyền thống trường. Nội dung nào nên ưu tiên để thể hiện đúng truyền thống nhà trường?",options:{A:"Những thành tích, hoạt động đẹp và các tấm gương tiêu biểu của trường",B:"Các tin đồn chưa được kiểm chứng về học sinh cũ",C:"Những chuyện riêng của từng gia đình học sinh",D:"Các trò chơi điện tử đang phổ biến"},correct_answer:"A"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Hoạt động sản xuất",source_unit:"Cộng đồng địa phương",source_lesson:"Bài 9. Hoạt động sản xuất nông nghiệp",skill_tag:["inference","production"],difficulty:"thông hiểu",type:"single_choice",question:"Một địa phương có cánh đồng rộng, hệ thống kênh mương và người dân chủ yếu trồng lúa, rau màu. Hoạt động sản xuất chính ở địa phương đó là gì?",options:{A:"Nông nghiệp",B:"Khai thác khoáng sản",C:"Làm phần mềm máy tính",D:"Vận tải hàng không"},correct_answer:"A"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Di tích và cảnh quan",source_unit:"Cộng đồng địa phương",source_lesson:"Bài 11. Di tích lịch sử - văn hoá và cảnh quan thiên nhiên",skill_tag:["matching","classification"],difficulty:"vận dụng",type:"matching",question:"Ghép địa điểm với loại địa điểm phù hợp.",items:[{label:"Đình làng cổ",correct_match:"Di tích lịch sử - văn hoá"},{label:"Thác nước nổi tiếng",correct_match:"Cảnh quan thiên nhiên"},{label:"Khu tưởng niệm anh hùng",correct_match:"Di tích lịch sử - văn hoá"}],option_pool:["Di tích lịch sử - văn hoá","Cảnh quan thiên nhiên"]},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Bộ phận của thực vật",source_unit:"Thực vật và động vật",source_lesson:"Bài 14. Chức năng một số bộ phận của thực vật",skill_tag:["application","biology"],difficulty:"vận dụng",type:"single_choice",question:"Một cây non bị đứt gần hết phần rễ nên dù được tưới nước thường xuyên vẫn héo dần. Giải thích nào phù hợp nhất?",options:{A:"Lá không còn quang hợp được vào ban ngày",B:"Rễ bị tổn thương nên cây hút nước và chất khoáng kém",C:"Hoa chưa nở nên cây không lớn lên",D:"Thân cây luôn có nhiệm vụ hút nước thay rễ"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Sử dụng hợp lí thực vật và động vật",source_unit:"Thực vật và động vật",source_lesson:"Bài 16. Sử dụng hợp lí thực vật và động vật",skill_tag:["behavior","environment"],difficulty:"vận dụng",type:"single_choice",question:"Ở khu du lịch sinh thái, hành động nào thể hiện sử dụng hợp lí thực vật và động vật?",options:{A:"Bẻ cành lan rừng mang về làm kỉ niệm",B:"Mua chim non bị bắt ngoài rừng để nuôi cho vui",C:"Quan sát, chụp ảnh và nhắc mọi người không làm hại cây, con vật",D:"Cho thú ăn theo sở thích của mình"},correct_answer:"C"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Cơ quan tiêu hoá",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 19. Chăm sóc và bảo vệ cơ quan tiêu hoá",skill_tag:["health","scenario"],difficulty:"vận dụng",type:"single_choice",question:"Sau buổi liên hoan, bạn An đau bụng vì ăn quá nhiều đồ cay và uống nước ngọt có ga. Việc nào giúp bảo vệ cơ quan tiêu hoá tốt hơn cho lần sau?",options:{A:"Ăn thật nhanh để còn chơi",B:"Ăn vừa đủ, chọn thức ăn hợp vệ sinh và hạn chế đồ quá cay",C:"Chỉ uống nước ngọt, không ăn rau",D:"Nhịn ăn sáng để tối ăn bù"},correct_answer:"B"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Cơ quan thần kinh",source_unit:"Con người và sức khoẻ",source_lesson:"Bài 23. Chăm sóc và bảo vệ cơ quan thần kinh",skill_tag:["health","habits"],difficulty:"thông hiểu",type:"single_choice",question:"Thói quen nào dưới đây có hại rõ nhất cho cơ quan thần kinh của học sinh tiểu học?",options:{A:"Ngủ đủ giấc và vận động mỗi ngày",B:"Đọc sách nơi đủ ánh sáng",C:"Thức khuya liên tục để chơi điện tử",D:"Trò chuyện với người thân"},correct_answer:"C"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Xác định phương hướng",source_unit:"Trái Đất và bầu trời",source_lesson:"Bài 26. Xác định các phương trong không gian",skill_tag:["application","direction"],difficulty:"vận dụng",type:"single_choice",question:"Buổi sáng, Mai đứng ở sân trường và quay mặt về phía Mặt Trời mọc. Khi đó bên tay trái của Mai là hướng nào?",options:{A:"Bắc",B:"Nam",C:"Đông",D:"Tây"},correct_answer:"A"},
  {grade:3,book:"Tự nhiên và Xã hội 3 - Kết nối tri thức",subject:"Tự nhiên và Xã hội",topic:"Trái Đất và khí hậu",source_unit:"Trái Đất và bầu trời",source_lesson:"Bài 27. Trái Đất và các đới khí hậu",skill_tag:["inference","weather"],difficulty:"thông hiểu",type:"single_choice",question:"Cùng một thời điểm, miền Bắc nước ta có thể rét hơn miền Nam. Nhận xét nào giải thích phù hợp nhất ở mức bài học lớp 3?",options:{A:"Mọi nơi trên Trái Đất luôn có thời tiết giống nhau",B:"Các khu vực khác nhau trên Trái Đất có đặc điểm khí hậu khác nhau",C:"Miền Bắc ở gần Mặt Trăng hơn miền Nam",D:"Nhiệt độ chỉ phụ thuộc vào số lượng nhà cao tầng"},correct_answer:"B"}
];
