module.exports = [
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn và câu chủ đề",source_unit:"Mỗi người một vẻ",source_lesson:"Bài 1. Điều kì diệu; Tìm hiểu đoạn văn và câu chủ đề",skill_tag:["reading","main-idea"],difficulty:"vận dụng",type:"single_choice",passage:"Mỗi sáng, bác bảo vệ đến trường từ rất sớm. Bác mở cổng, quét sân rồi kiểm tra từng dãy lớp học. Nhờ có bác, ngôi trường luôn sạch sẽ, an toàn trước giờ vào học.",question:"Câu nào nêu đúng nhất ý chính của đoạn văn?",options:{A:"Bác bảo vệ làm nhiều việc để giữ trường sạch sẽ, an toàn.",B:"Sân trường rất rộng.",C:"Học sinh đến lớp rất đông.",D:"Buổi sáng thường có gió mát."},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn nêu ý kiến",source_unit:"Mỗi người một vẻ",source_lesson:"Bài 2 đến Bài 5. Đoạn văn nêu ý kiến",skill_tag:["writing","argument"],difficulty:"vận dụng",type:"single_choice",question:"Để làm rõ ý kiến 'Nên đọc sách mỗi ngày', lí lẽ nào thuyết phục nhất?",options:{A:"Đọc sách giúp mở rộng hiểu biết và rèn thói quen suy nghĩ",B:"Nhiều cuốn sách có bìa đẹp",C:"Thư viện trường ở gần lớp em",D:"Bạn em cũng thích đọc sách"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Từ điển",source_unit:"Trải nghiệm và khám phá",source_lesson:"Bài 15. Cách dùng và công dụng của từ điển",skill_tag:["dictionary","ordering"],difficulty:"thông hiểu",type:"single_choice",question:"Khi tra ba từ 'học tập', 'học hỏi', 'học sinh' trong từ điển, em cần nhớ điều gì để tìm nhanh?",options:{A:"Chỉ nhìn độ dài của từ",B:"So sánh lần lượt từng tiếng theo thứ tự bảng chữ cái",C:"Mở ngẫu nhiên một trang bất kì",D:"Tìm từ nào có nét chữ đẹp hơn"},correct_answer:"B"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Nhân hoá",source_unit:"Niềm vui sáng tạo",source_lesson:"Bài 17. Biện pháp nhân hoá",skill_tag:["language","effect"],difficulty:"thông hiểu",type:"single_choice",passage:"Những hàng cây bên đường dang tay đón gió sớm, ríu rít trò chuyện cùng chim chóc.",question:"Biện pháp nhân hoá trong câu trên có tác dụng nổi bật nhất là gì?",options:{A:"Làm cho cảnh vật trở nên sống động, gần gũi như con người",B:"Chứng minh cây biết nói thật",C:"Cho biết tên loài cây bên đường",D:"Thay thế hoàn toàn việc quan sát thực tế"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Hai thành phần chính của câu",source_unit:"Sống để yêu thương",source_lesson:"Bài 3. Hai thành phần chính của câu",skill_tag:["grammar","sentence-analysis"],difficulty:"vận dụng",type:"single_choice",question:"Trong câu 'Những cánh buồm trắng nhỏ dần sau cửa biển.', đâu là chủ ngữ?",options:{A:"Nhỏ dần sau cửa biển",B:"Những cánh buồm trắng",C:"Sau cửa biển",D:"Trắng nhỏ dần"},correct_answer:"B"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Chủ ngữ",source_unit:"Sống để yêu thương",source_lesson:"Bài 5. Luyện tập về chủ ngữ",skill_tag:["grammar","application"],difficulty:"vận dụng",type:"single_choice",question:"Câu nào dưới đây có chủ ngữ là một cụm từ chứ không phải chỉ một từ đơn?",options:{A:"Mưa rơi.",B:"Đàn chim sẻ ríu ran trên mái ngói.",C:"Em học bài.",D:"Nắng lên."},correct_answer:"B"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Hướng dẫn sử dụng",source_unit:"Sống để yêu thương",source_lesson:"Bài 7, 8. Viết hướng dẫn sử dụng một sản phẩm",skill_tag:["writing","procedural-text"],difficulty:"vận dụng",type:"single_choice",question:"Muốn viết hướng dẫn sử dụng bình nước cá nhân rõ ràng, trình tự nào hợp lí nhất?",options:{A:"Nêu bước thực hiện theo thứ tự, dùng câu ngắn gọn, dễ làm theo",B:"Chỉ kể cảm xúc của mình về chiếc bình",C:"Liệt kê ngẫu nhiên các ý nghĩ ra được",D:"Viết thật dài nhưng không đánh số bước"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Trạng ngữ",source_unit:"Uống nước nhớ nguồn",source_lesson:"Bài 11, 13, 15. Trạng ngữ",skill_tag:["grammar","distinguish"],difficulty:"vận dụng",type:"single_choice",question:"Trong câu 'Sáng sớm, trên sân đình, tiếng trống hội vang lên rộn rã.', bộ phận nào là trạng ngữ chỉ nơi chốn?",options:{A:"Sáng sớm",B:"Trên sân đình",C:"Tiếng trống hội",D:"Vang lên rộn rã"},correct_answer:"B"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Dấu ngoặc kép",source_unit:"Quê hương trong tôi",source_lesson:"Bài 19. Dấu ngoặc kép",skill_tag:["punctuation","usage"],difficulty:"thông hiểu",type:"single_choice",question:"Trường hợp nào cần dùng dấu ngoặc kép?",options:{A:"Đánh dấu lời nói trực tiếp của nhân vật",B:"Ngăn cách trạng ngữ với chủ ngữ",C:"Nối các tiếng trong tên riêng nước ngoài phiên âm",D:"Kết thúc câu kể"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Miêu tả cây cối",source_unit:"Quê hương trong tôi",source_lesson:"Bài 17 đến Bài 24. Viết bài văn miêu tả cây cối",skill_tag:["writing","description"],difficulty:"vận dụng",type:"single_choice",question:"Khi tả cây phượng ở sân trường, chi tiết nào giúp đoạn văn sinh động hơn cả?",options:{A:"Cây cao khoảng bao nhiêu mét là đủ",B:"Màu hoa, tiếng ve, bóng mát và cảm xúc của em khi đứng dưới tán cây",C:"Tên người bán cây ở chợ",D:"Số hiệu lớp học gần cây"},correct_answer:"B"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn tưởng tượng",source_unit:"Vì một thế giới bình yên",source_lesson:"Bài 25, 26, 27. Viết đoạn văn tưởng tượng",skill_tag:["creativity","consistency"],difficulty:"vận dụng",type:"single_choice",question:"Muốn đoạn văn tưởng tượng vẫn hợp lí và hấp dẫn, em nên làm gì?",options:{A:"Tưởng tượng tự do nhưng các chi tiết vẫn cần gắn với một tình huống rõ ràng",B:"Viết bất cứ điều gì, không cần liên kết",C:"Chỉ chép lại một đoạn văn mẫu",D:"Không dùng cảm xúc hay hình ảnh nào"},correct_answer:"A"},
  {grade:4,book:"Tiếng Việt 4 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đọc hiểu",source_unit:"Sống để yêu thương",source_lesson:"Bài 1 đến Bài 8",skill_tag:["reading","emotion"],difficulty:"vận dụng",type:"short_answer",passage:"Mẹ đi làm về muộn. Thấy chiếc cốc nước ấm và mảnh giấy nhỏ ghi 'Mẹ nghỉ một lát nhé!', mẹ mỉm cười rất lâu.",question:"Nêu ngắn gọn ý chính của đoạn văn trên.",correct_answer:"Bạn nhỏ biết quan tâm, yêu thương mẹ",accepted_answers:["Bạn nhỏ biết quan tâm, yêu thương mẹ","Sự quan tâm của bạn nhỏ dành cho mẹ","Bạn nhỏ chăm sóc mẹ"]}
];
