module.exports = [
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đại từ",source_unit:"Thế giới tuổi thơ",source_lesson:"Bài 3, 4. Luyện tập về đại từ",skill_tag:["grammar","reference"],difficulty:"vận dụng",type:"single_choice",passage:"Lan nhặt được ví tiền trước cổng trường. Em liền nhờ cô tổng phụ trách tìm người đánh rơi và trả lại ngay trong buổi sáng ấy.",question:"Từ 'Em' trong đoạn văn dùng để thay thế cho từ ngữ nào?",options:{A:"Cô tổng phụ trách",B:"Người đánh rơi",C:"Lan",D:"Ví tiền"},correct_answer:"C"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Từ nhiều nghĩa",source_unit:"Thiên nhiên kì thú",source_lesson:"Bài 11. Luyện tập về từ nhiều nghĩa",skill_tag:["semantics","context"],difficulty:"vận dụng",type:"single_choice",question:"Từ 'chín' trong câu nào được dùng với nghĩa gốc?",options:{A:"Suy nghĩ của bạn ấy đã chín chắn hơn nhiều.",B:"Những quả xoài trong vườn đã chín vàng.",C:"Đó là một kế hoạch chín muồi.",D:"Bài viết của bạn đã chín ý rồi."},correct_answer:"B"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Liên kết câu bằng lặp từ ngữ",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 23. Liên kết câu bằng cách lặp từ ngữ",skill_tag:["cohesion","text"],difficulty:"thông hiểu",type:"single_choice",passage:"Dòng sông quê tôi hiền hoà quanh năm. Dòng sông ấy bồi đắp phù sa cho bãi ngô xanh tốt.",question:"Hai câu trong đoạn văn liên kết với nhau chủ yếu bằng cách nào?",options:{A:"Lặp từ ngữ",B:"Dùng từ trái nghĩa",C:"Dùng dấu hai chấm",D:"Dùng câu hỏi"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Liên kết câu bằng từ ngữ nối",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 24. Liên kết câu bằng từ ngữ nối",skill_tag:["cohesion","logic"],difficulty:"vận dụng",type:"single_choice",question:"Từ nối nào thích hợp nhất để hoàn chỉnh câu sau: 'Mưa đã ngớt, ... các cô chú công nhân vẫn khẩn trương dọn cây gãy trên đường.'",options:{A:"nhưng",B:"vì",C:"nên",D:"nếu"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Liên kết câu trong đoạn văn",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 25. Luyện tập về liên kết câu trong đoạn văn",skill_tag:["cohesion","editing"],difficulty:"vận dụng",type:"single_choice",question:"Để đoạn văn sau mạch lạc hơn, em nên chọn câu nào đặt ở cuối đoạn? 'Sáng nào ông cũng dậy sớm tưới cây. Ông chăm từng gốc hồng, gốc cúc rất tỉ mỉ. ...'",options:{A:"Nhờ vậy, khu vườn nhỏ trước nhà luôn rực rỡ sắc hoa.",B:"Em thích ăn kem vào mùa hè.",C:"Con mèo nhà em rất nghịch.",D:"Hôm nay là thứ ba."},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Câu ghép",source_unit:"Vẻ đẹp cuộc sống",source_lesson:"Bài 1, 3, 5, 7. Câu đơn và câu ghép; Cách nối các vế câu ghép",skill_tag:["grammar","relation"],difficulty:"vận dụng",type:"single_choice",question:"Câu ghép nào thể hiện quan hệ nguyên nhân - kết quả?",options:{A:"Tuy trời mưa nhưng chúng em vẫn đến lớp.",B:"Vì bạn Nam chăm chỉ nên bạn ấy tiến bộ rõ rệt.",C:"Nếu trời nắng thì em đi bơi.",D:"Mưa tạnh và nắng lên."},correct_answer:"B"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn nêu ý kiến tán thành",source_unit:"Tiếp bước cha ông",source_lesson:"Bài 17 đến Bài 21. Viết đoạn văn nêu ý kiến tán thành một sự việc, hiện tượng",skill_tag:["argument","writing"],difficulty:"vận dụng",type:"single_choice",question:"Để nêu ý kiến tán thành việc trồng cây trong trường học, dẫn chứng nào phù hợp nhất?",options:{A:"Cây làm trường mát hơn, đẹp hơn và giúp học sinh có ý thức bảo vệ môi trường",B:"Nhiều bạn thích chụp ảnh với cây",C:"Cây thường có màu xanh",D:"Một số cây có tên rất lạ"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Đoạn văn nêu ý kiến phản đối",source_unit:"Thế giới của chúng ta",source_lesson:"Bài 27 đến Bài 30. Viết đoạn văn nêu ý kiến phản đối một sự việc, hiện tượng",skill_tag:["argument","critical-thinking"],difficulty:"vận dụng",type:"single_choice",question:"Khi viết đoạn văn phản đối việc lãng phí nước, cách lập luận nào thuyết phục nhất?",options:{A:"Chỉ khẳng định 'lãng phí nước là xấu' nhiều lần",B:"Nêu tác hại của việc lãng phí nước và đề xuất cách tiết kiệm cụ thể",C:"Kể tên tất cả các con sông em biết",D:"Chuyển sang nói về môn thể thao yêu thích"},correct_answer:"B"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Thể hiện tình cảm, cảm xúc",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 23, 24. Tìm hiểu cách viết đoạn văn thể hiện tình cảm, cảm xúc về một sự việc",skill_tag:["emotion","writing"],difficulty:"vận dụng",type:"single_choice",question:"Câu nào thể hiện cảm xúc chân thật và rõ nhất trước một việc tốt?",options:{A:"Các bạn lớp em quyên góp sách vào chiều thứ sáu.",B:"Em xúc động và khâm phục khi thấy các bạn âm thầm quyên góp sách cho thư viện vùng cao.",C:"Thư viện ở tầng hai của trường.",D:"Chiều thứ sáu trời rất mát."},correct_answer:"B"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Chương trình hoạt động",source_unit:"Hương sắc trăm miền",source_lesson:"Bài 25, 26. Viết chương trình hoạt động",skill_tag:["functional-writing","planning"],difficulty:"thông hiểu",type:"single_choice",question:"Mục nào không thể thiếu trong một chương trình hoạt động của lớp?",options:{A:"Thời gian, địa điểm, nội dung, phân công",B:"Sở thích riêng của từng người viết",C:"Màu bút dùng để viết bản nháp",D:"Danh sách các bộ phim yêu thích"},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Viết hoa danh từ chung thể hiện sự tôn trọng",source_unit:"Tiếp bước cha ông",source_lesson:"Bài 23. Viết hoa danh từ chung để thể hiện sự tôn trọng đặc biệt",skill_tag:["orthography","respect"],difficulty:"vận dụng",type:"single_choice",question:"Trong câu nào dưới đây, cách viết hoa thể hiện sự tôn trọng đặc biệt là đúng?",options:{A:"Chúng em luôn biết ơn các chú bộ đội và Bác Hồ.",B:"Chúng em luôn biết ơn Các Chú Bộ Đội.",C:"Chúng em luôn biết ơn bác hồ.",D:"Chúng em luôn biết ơn Bác hồ."},correct_answer:"A"},
  {grade:5,book:"Tiếng Việt 5 - Kết nối tri thức",subject:"Tiếng Việt",topic:"Nêu ý chính",source_unit:"Vẻ đẹp cuộc sống",source_lesson:"Bài 1 đến Bài 8",skill_tag:["reading","main-idea"],difficulty:"vận dụng",type:"short_answer",passage:"Bố em là thợ sửa xe. Mỗi chiều đi làm về, bố vẫn dành thời gian kiểm tra lại xe đạp cho hai chị em trước khi chúng em đến lớp ngày mai. Em hiểu rằng trong những việc nhỏ ấy có biết bao sự chăm lo thầm lặng.",question:"Nêu ý chính của đoạn văn bằng một cụm ngắn.",correct_answer:"Sự chăm lo thầm lặng của người bố",accepted_answers:["Sự chăm lo thầm lặng của người bố","Bố âm thầm chăm lo cho con","Tình thương thầm lặng của bố"]}
];
